import { it as test } from 'vitest';
import { strict as assert } from 'node:assert';
import { createCodexRlmExecChildRunner,buildToolFreeCodexExecArgs } from './codexRlmExecChild';
const runtime={executableId:'cli-executable-4',executableSha256:'a'.repeat(64),version:'0.159.2',profileGeneration:'fixture-profile',authBillingRoute:'fixture-chatgpt-subscription',configPolicyGeneration:'c'.repeat(64),isolatedWorkingDirectory:'C:/task-fixture/empty'};
const capability={...runtime,authenticatedProfileVerified:true,positiveControlVerified:true,negativeAppsVerified:true,negativeBuiltinsVerified:true,binaryConfigProofScope:'pinned-binary-config-loopback',binaryConfigCertificateHash:'c'.repeat(64),authenticatedModelControlsVerified:false,modelIds:['gpt-6-luna'],efforts:['low'],fastVariants:['standard','fast']};
function request(controller=new AbortController()): any{return {question:'What is the synthetic code?',evidence:[],sourcePointers:[{id:'safe-pointer'}],depth:1,budget:{maxInputTokens:2000,maxOutputTokens:1000},signal:controller.signal,executionIdentity:{transportConnectionId:'openai-codex',transportAdapterId:'codex-app-server',upstreamProviderId:'openai',upstreamModelId:'gpt-6-luna',providerQualifiedModelId:'openai/gpt-6-luna',authBillingRoute:runtime.authBillingRoute,effort:'low',fastVariant:'standard',catalogRevision:'fixture'}};}
function deps(overrides: any = {}): any{const calls=[];return {calls,parentRuntime:async()=>runtime,capability:async()=>capability,cancel:async (id: any)=>{calls.push(['cancel',id]);return true;},requestId:()=> 'child-fixture',stream:async function*(this: any, r: any){calls.push(['start',r]);yield{requestId:r.requestId,stream:'status',status:'started'};const data=JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'SAFE-42'}})+'\n'+JSON.stringify({type:'turn.completed',usage:{}})+'\n';yield{requestId:r.requestId,stream:'stdout',status:'data',data};yield{requestId:r.requestId,stream:'status',status:'completed',exitCode:0};},...overrides};}
test('independent bridge send retains exact runtime/model/effort/auth and bounded ephemeral fixed policy',async()=>{const d=deps(),out=await createCodexRlmExecChildRunner(d)(request());assert.equal(out.answer,'SAFE-42');assert.equal(out.citations[0].id,'safe-pointer');const r=d.calls[0][1];assert.equal(r.executableId,runtime.executableId);assert.equal(r.timeoutMs,30000);assert.equal(r.cwd,runtime.isolatedWorkingDirectory);assert.equal(r.toolScope,undefined);assert.ok(r.args.includes('features.apps=false'));assert.ok(r.args.includes('forced_login_method="chatgpt"'));assert.ok(r.args.includes('--ignore-user-config'));assert.ok(r.args.includes('model_reasoning_effort="low"'));});
test('fast preserves service tier only when exact verified capability permits it',async()=>{const r=request();r.executionIdentity.fastVariant='fast';const d=deps();await createCodexRlmExecChildRunner(d)(r);assert.ok(d.calls[0][1].args.includes('service_tier="priority"'));assert.throws(()=>buildToolFreeCodexExecArgs('gpt-6-luna','low','turbo'),/fast_unavailable/);});
test('observed native priority tier uses exact priority encoding without accepting plain provider identity',async()=>{const r=request();r.executionIdentity.fastVariant='priority';const d=deps({capability:async()=>({...capability,fastVariants:['priority']})});await createCodexRlmExecChildRunner(d)(r);assert.ok(d.calls[0][1].args.includes('service_tier="priority"'));const bad=request();bad.executionIdentity.providerQualifiedModelId='gpt-6-luna';await assert.rejects(createCodexRlmExecChildRunner(deps())(bad),/exact_codex_route/);});
test('no OpenCode or different upstream fallback',async()=>{const r=request();r.executionIdentity.transportAdapterId='opencode-persistent';const d=deps();await assert.rejects(createCodexRlmExecChildRunner(d)(r),/exact_codex_route/);assert.equal(d.calls.length,0);});
test('isolated-only or missing positive capability never dispatches',async()=>{const d=deps({capability:async()=>({...capability,authenticatedProfileVerified:false})});await assert.rejects(createCodexRlmExecChildRunner(d)(request()),/capability_unverified/);assert.equal(d.calls.length,0);});
test('missing or mismatched binary-config proof scope cannot dispatch',async()=>{for(const patch of [{binaryConfigProofScope:'frontend-claim'},{binaryConfigCertificateHash:'d'.repeat(64)}]){const d=deps({capability:async()=>({...capability,...patch})});await assert.rejects(createCodexRlmExecChildRunner(d)(request()),/certificate_unverified/);assert.equal(d.calls.length,0);}});
test('changed executable/profile invalidates capability before send',async()=>{const d=deps({capability:async()=>({...capability,executableSha256:'b'.repeat(64)})});await assert.rejects(createCodexRlmExecChildRunner(d)(request()),/capability_mismatch/);assert.equal(d.calls.length,0);});
test('different billing route or unverified model is rejected before send',async()=>{const r=request();r.executionIdentity.authBillingRoute='fixture-api-key';const d=deps();await assert.rejects(createCodexRlmExecChildRunner(d)(r),/identity_unavailable/);assert.equal(d.calls.length,0);});
test('tool item cancels and drains native reaped terminal before rejecting',async()=>{const d=deps({stream:async function*(this: any, r: any){yield{requestId:r.requestId,stream:'status',status:'started'};yield{requestId:r.requestId,stream:'stdout',status:'data',data:JSON.stringify({type:'item.started',item:{type:'command_execution'}})+'\n'};yield{requestId:r.requestId,stream:'status',status:'cancelled',exitCode:1};}});await assert.rejects(createCodexRlmExecChildRunner(d)(request()),/cancelled|tool_exposure/);assert.equal(d.calls[0][0],'cancel');});
test('owner abort waits for actual cancelled terminal',async()=>{const c=new AbortController(),d=deps({stream:async function*(this: any, r: any){yield{requestId:r.requestId,stream:'status',status:'started'};c.abort();yield{requestId:r.requestId,stream:'status',status:'cancelled',exitCode:1};}});await assert.rejects(createCodexRlmExecChildRunner(d)(request(c)),/rlm_cancelled/);assert.equal(d.calls[0][0],'cancel');});
test('lost terminal acknowledgement poisons further admission instead of overlapping child',async()=>{const d=deps({stream:async function*(this: any, r: any){yield{requestId:r.requestId,stream:'status',status:'started'};throw Error('stream lost');}}),run=createCodexRlmExecChildRunner(d);await assert.rejects(run(request()),/abort_unconfirmed/);await assert.rejects(run(request()),/resource_busy/);});
test('duplicate completion or model mismatch fails with no successful analysis',async()=>{for(const tail of [{type:'turn.completed'},{type:'turn.completed',model:'wrong-model'}]){const d=deps({stream:async function*(this: any, r: any){yield{requestId:r.requestId,stream:'status',status:'started'};yield{requestId:r.requestId,stream:'stdout',status:'data',data:JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'safe'}})+'\n'+JSON.stringify({type:'turn.completed'})+'\n'+JSON.stringify(tail)+'\n'};yield{requestId:r.requestId,stream:'status',status:'cancelled',exitCode:1};}});await assert.rejects(createCodexRlmExecChildRunner(d)(request()),/duplicate_completion|model_mismatch/);}});
test('oversized evidence fails before native process allocation',async()=>{const r=request();r.question='x'.repeat(150000);const d=deps();await assert.rejects(createCodexRlmExecChildRunner(d)(r),/input_budget/);assert.equal(d.calls.length,0);});
