import { it as test } from 'vitest';
import { strict as assert } from 'node:assert';
import { registerLiveCodexRlmParent, readLiveCodexRlmParent } from './codexRlmParentBinding';
let sequence=0;
function fixture(): any {const generation='fixture-generation-'+(++sequence);const identity={transportConnectionId:'openai-codex',transportAdapterId:'codex-cli',upstreamProviderId:'openai',upstreamModelId:'gpt-6-luna',providerQualifiedModelId:'openai/gpt-6-luna',observedProviderIdentity:'openai/gpt-6-luna',authBillingRoute:'codex-cli-session',effort:'low',fastVariant:'standard',catalogRevision:generation};let calls=0;const parent={caller:'main',owner:'fixture-chat',generation,identity,active:()=>true,accountRead:async()=>{calls++;return {result:{requiresOpenaiAuth:true,account:{type:'chatgpt',email:'fixture@example.invalid'}}};}};return{identity,parent,request:{executionIdentity:identity,signal:new AbortController().signal},calls:()=>calls};}
test('live parent reader supplies private RPC and returns only native ownership tuple',async()=>{const f=fixture(),release=registerLiveCodexRlmParent(f.parent);try{const result=await readLiveCodexRlmParent(f.request);assert.deepEqual(result,{caller:'main',owner:'fixture-chat',generation:f.parent.generation});assert.equal(f.calls(),1);assert.ok(!JSON.stringify(result).includes('@'));}finally{release();}});
test('released generation rejected without account RPC',async()=>{const f=fixture(),release=registerLiveCodexRlmParent(f.parent);release();await assert.rejects(readLiveCodexRlmParent(f.request),/unavailable/);assert.equal(f.calls(),0);});
test('mismatched original model effort tier or observed identity rejected before RPC',async()=>{const f=fixture(),release=registerLiveCodexRlmParent(f.parent);try{for(const patch of [{upstreamModelId:'other'},{effort:'high'},{fastVariant:'priority'},{observedProviderIdentity:'openai/other'}])await assert.rejects(readLiveCodexRlmParent({...f.request,executionIdentity:{...f.identity,...patch}}),/unavailable/);assert.equal(f.calls(),0);}finally{release();}});
test('parent abort and child abort each reject without RPC',async()=>{for(const child of [false,true]){const f=fixture(),c=new AbortController();c.abort();if(!child)f.parent.signal=c.signal;const release=registerLiveCodexRlmParent(f.parent);try{await assert.rejects(readLiveCodexRlmParent({...f.request,...(child?{signal:c.signal}:{})}),/unavailable/);assert.equal(f.calls(),0);}finally{release();}}});
test('termination while account response is pending rejects delivery',async()=>{const f=fixture();let active=true;f.parent.active=()=>active;f.parent.accountRead=async()=>{active=false;return{result:{requiresOpenaiAuth:true,account:{type:'chatgpt',email:'fixture@example.invalid'}}};};const release=registerLiveCodexRlmParent(f.parent);try{await assert.rejects(readLiveCodexRlmParent(f.request),/changed/);}finally{release();}});
test('plan/type alone or API account cannot establish subscription binding',async()=>{for(const account of [{type:'chatgpt',planType:'pro'},{type:'apiKey'}]){const f=fixture();f.parent.accountRead=async()=>({result:{requiresOpenaiAuth:true,account}});const release=registerLiveCodexRlmParent(f.parent);try{await assert.rejects(readLiveCodexRlmParent(f.request),/subscription_unverified/);}finally{release();}}});
test('caller model cannot replace frozen registered execution identity',async()=>{const f=fixture(),release=registerLiveCodexRlmParent(f.parent);try{f.identity.effort='high';await assert.rejects(readLiveCodexRlmParent(f.request),/unavailable/);}finally{release();}});
test('uncanonical plain provider identity rejected at registration',()=>{const f=fixture();f.parent.identity={...f.identity,providerQualifiedModelId:'gpt-6-luna'};assert.throws(()=>registerLiveCodexRlmParent(f.parent),/invalid/);});
test('duplicate generation cannot steal or release another owner',async()=>{const f=fixture(),release=registerLiveCodexRlmParent(f.parent);try{assert.throws(()=>registerLiveCodexRlmParent({...f.parent,owner:'other'}),/invalid/);assert.equal((await readLiveCodexRlmParent(f.request)).owner,'fixture-chat');}finally{release();}});
