import { it as test } from 'vitest';
import { strict as assert } from 'node:assert';
import { createNativeBoundCodexRlmChild } from './codexRlmNativeFactory';
const parent={caller:'main',owner:'fixture-chat',generation:'fixture-parent'};
const runtime={executableId:'cli-executable-4',executableSha256:'a'.repeat(64),version:'0.159.2',profileGeneration:'fixture-profile',authBillingRoute:'fixture-chatgpt',configPolicyGeneration:'c'.repeat(64),isolatedWorkingDirectory:'C:/fixture/private-empty'};
const proof={authorityHandle:'codex-rlm-authority-'+ 'A'.repeat(24),parent,runtime,accountHash:'b'.repeat(64),sameUniqueAccount:true,capability:{...runtime,authenticatedProfileVerified:true,positiveControlVerified:true,negativeAppsVerified:true,negativeBuiltinsVerified:true,binaryConfigProofScope:'pinned-binary-config-loopback',binaryConfigCertificateHash:'c'.repeat(64),authenticatedModelControlsVerified:false,modelIds:['gpt-6-luna'],efforts:['low'],fastVariants:['standard']}};
const request=()=>({question:'Synthetic?',evidence:[],sourcePointers:[],depth:1,budget:{},signal:new AbortController().signal,executionIdentity:{transportConnectionId:'openai-codex',transportAdapterId:'codex-app-server',upstreamProviderId:'openai',upstreamModelId:'gpt-6-luna',providerQualifiedModelId:'openai/gpt-6-luna',authBillingRoute:'fixture-chatgpt',effort:'low',fastVariant:'standard'}});
function native(p=proof): any{return {calls:[] as any[],prepare:async()=>p,revoke:async function(this: any, id: any){this.calls.push(['revoke',id]);},cancel:async()=>true,stream:async function*(this: any, r: any){this.calls.push(['start',r]);yield{requestId:r.requestId,stream:'status',status:'started'};yield{requestId:r.requestId,stream:'stdout',status:'data',data:JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'SAFE'}})+'\n'+JSON.stringify({type:'turn.completed'})+'\n'};yield{requestId:r.requestId,stream:'status',status:'completed',exitCode:0};}};}
test('native command receives one-use authority and bounded prompt without arbitrary args/path/env',async()=>{const n=native(),run=createNativeBoundCodexRlmChild(n,async()=>parent,()=> 'child');assert.equal((await run(request())).answer,'SAFE');const sent=n.calls.find(x=>x[0]==='start')[1];assert.deepEqual(Object.keys(sent).sort(),['authorityHandle','outputLimitBytes','prompt','requestId','timeoutMs'].sort());assert.equal(n.calls.at(-1)[0],'revoke');});
test('different native parent generation is rejected and revoked before dispatch',async()=>{const n=native({...proof,parent:{...parent,generation:'other'}});await assert.rejects(createNativeBoundCodexRlmChild(n,async()=>parent,()=> 'child')(request()),/authority_unverified/);assert.deepEqual(n.calls.map(x=>x[0]),['revoke']);});
test('plan/type without unique account proof never starts',async()=>{const n=native({...proof,sameUniqueAccount:false});await assert.rejects(createNativeBoundCodexRlmChild(n,async()=>parent,()=> 'child')(request()),/authority_unverified/);assert.ok(!n.calls.some(x=>x[0]==='start'));});
test('isolated capability never starts even with account hash',async()=>{const n=native({...proof,capability:{...proof.capability,authenticatedProfileVerified:false}});await assert.rejects(createNativeBoundCodexRlmChild(n,async()=>parent,()=> 'child')(request()),/capability_unverified/);assert.deepEqual(n.calls.map(x=>x[0]),['revoke']);});
test('unsupported native command does not silently use generic bridge',async()=>{const n=native();n.prepare=async()=>{throw Error('unknown native command');};await assert.rejects(createNativeBoundCodexRlmChild(n,async()=>parent,()=> 'child')(request()),/unknown native command/);assert.equal(n.calls.length,0);});
test('concurrent rejection cannot revoke the admitted child authority',async()=>{const n=native();let release: any;const wait=new Promise(r=>release=r);const original=n.stream;n.stream=async function*(this: any, r: any){await wait;yield* original.call(this,r);};const run=createNativeBoundCodexRlmChild(n,async()=>parent,()=> 'child');const first=run(request());await new Promise(r=>setImmediate(r));await assert.rejects(run(request()),/resource_busy/);assert.equal(n.calls.length,0);release();await first;assert.equal(n.calls.filter(x=>x[0]==='revoke').length,1);});
