/* This file is generated by scripts/visual-monochrome/generate-theme-contract.mjs. */
/* Do not edit by hand. Edit themeContract.source.json and regenerate. */

export const THEME_STORAGE_KEY = 'jarvis-ui';
export const UI_STORE_VERSION = 5;
export const THEME_FALLBACK_ID = 'default';

export const SELECTABLE_THEME_IDS = [
  'jarvis',
  'vibespace',
  'default',
  'monochrome',
  'sakura',
  'warm',
  'origami',
] as const;
export type SelectableTheme = (typeof SELECTABLE_THEME_IDS)[number];

export const DEFERRED_THEME_IDS = ['vibespace', 'sakura', 'origami'] as const;
export const RELEASE_THEME_IDS = ['jarvis', 'default', 'monochrome', 'warm'] as const;

export const THEME_DEFINITIONS = [
  { id: 'jarvis', label: 'Jarvis One', description: 'High-contrast command center.' },
  { id: 'vibespace', label: 'VibeSpace', description: 'Pastel origami workspace.' },
  { id: 'default', label: 'Default', description: 'Warm, focused dark workspace.' },
  { id: 'monochrome', label: 'MonoChrome', description: 'Terminal-inspired developer console.' },
  { id: 'sakura', label: 'Sakura', description: 'Cel-painted dusk workspace.' },
  { id: 'warm', label: 'Warm', description: 'Espresso and ivory paper workspace.' },
  { id: 'origami', label: 'Origami', description: 'Sculpted paper workspace in motion.' },
] as const;
export type ThemeDefinition = (typeof THEME_DEFINITIONS)[number];

export const RELEASE_THEME_DEFINITIONS = [
  { id: 'jarvis', label: 'Jarvis One', description: 'High-contrast command center.' },
  { id: 'default', label: 'Default', description: 'Warm, focused dark workspace.' },
  { id: 'monochrome', label: 'MonoChrome', description: 'Terminal-inspired developer console.' },
  { id: 'warm', label: 'Warm', description: 'Espresso and ivory paper workspace.' },
] as const;

export const DOCUMENT_THEME_BY_ID = {
  jarvis: 'jarvis',
  vibespace: 'vibespace',
  default: 'dark',
  monochrome: 'monochrome',
  sakura: 'sakura',
  warm: 'warm',
  origami: 'origami',
} as const;
export type ResolvedDocumentTheme =
  (typeof DOCUMENT_THEME_BY_ID)[keyof typeof DOCUMENT_THEME_BY_ID];

export const PERSISTED_LEGACY_THEME_MAP = {
  light: 'monochrome',
  dark: 'default',
  system: 'default',
} as const;
export type LegacyPersistedThemeId = keyof typeof PERSISTED_LEGACY_THEME_MAP;

export const SYNC_LEGACY_THEME_MAP = {
  light: 'monochrome',
} as const;

export const THEME_COMMAND_ALIASES = {
  jarvis: 'jarvis',
  'jarvis core': 'jarvis',
  'jarvis one': 'jarvis',
  core: 'jarvis',
  default: 'default',
  dark: 'default',
  monochrome: 'monochrome',
  mono: 'monochrome',
  terminal: 'monochrome',
  light: 'monochrome',
  warm: 'warm',
  cozy: 'warm',
} as const;
