export const JARVIS_COMMAND_CATALOG = [
  'open codex',
  'open claude',
  'open opencode',
  'open llm',
  'message terminal 3: run npm test',
  'Codex, review the updater',
  'tell OpenCode to fix the RLM tests',
  'tell all terminals to run git status',
  'tell all Codex terminals to inspect regressions',
  'create schedule release review friday at 1pm',
  'ask opencode to review this project',
  'ask claude to fix the failing tests',
  'ask codex to explain this error',
  'give all terminals all context',
  'create context map',
  'generate context map',
  'recenter context map',
  'open files',
  'open terminals',
  'open kanban',
  'open context',
  'open tools',
  'open history',
  'open agents',
  'open schedule',
  'create project tiger',
  'switch to tiger project',
  'create chat called planning',
  'open 4 terminals with opencode',
  'open claude in tiger',
  'create project tiger then open 4 terminals with opencode',
  'make a todo: verify the release tomorrow',
  'schedule standup friday at 1pm',
  'call me at 3pm',
  'message me: build is done',
  'ambient mode on',
  'ambient mode off',
  'fullscreen',
  'exit fullscreen',
  'open settings',
  'open providers',
  'open launcher',
  'show benchmarks',
  'show chat',
  'open terminal swarm',
  'ask groq to summarize the terminal',
  'ask gemini to draft release notes',
  'ask openai to make a migration plan',
  'ask anthropic to audit the architecture',
  'ask cursor to inspect file references',
  'create task ship installer today',
  'create task update docs tomorrow',
  'schedule release review monday',
  'open project settings',
  'open local models',
  'open phone voice settings',
  'switch voice to deepgram',
  'open voice settings and use Jarvis High',
  'set voice engine to system',
  'turn on ambient mode',
  'turn off ambient mode',
  'toggle fullscreen',
  'message me: remind me to test Jarvis',
  'close the inspector',
  'show the inspector',
  'toggle the inspector',
] as const;
