export const JARVIS_COMMAND_CATALOG = [
  'ask opencode to review this project',
  'ask claude to fix the failing tests',
  'ask codex to explain this error',
  'give all terminals all context',
  'create context map',
  'generate context map',
  'recenter context map',
  'open files',
  'open terminals',
  'open kanban',
  'open context',
  'open tools',
  'open history',
  'open agents',
  'open schedule',
  'create project tiger',
  'switch to tiger project',
  'create chat called planning',
  'open 4 terminals with opencode',
  'open claude in tiger',
  'run npm test in all terminals',
  'create command dev server to run npm run dev',
  'run command dev server',
  'create project tiger then open 4 terminals with opencode',
  'make a todo: verify the release tomorrow',
  'schedule standup friday at 1pm',
  'call me at 3pm',
  'message me: build is done',
  'ambient mode on',
  'ambient mode off',
  'fullscreen',
  'exit fullscreen',
  'open settings',
  'open providers',
  'open launcher',
  'show benchmarks',
  'show chat',
  'open terminal swarm',
  'run pnpm install in all terminals',
  'run npm run build in all terminals',
  'run git status in all terminals',
  'ask groq to summarize the terminal',
  'ask gemini to draft release notes',
  'ask openai to make a migration plan',
  'ask anthropic to audit the architecture',
  'ask cursor to inspect file references',
  'create task ship installer today',
  'create task update docs tomorrow',
  'schedule release review monday',
  'open project settings',
  'open local models',
  'open phone voice settings',
  'turn on ambient mode',
  'turn off ambient mode',
  'toggle fullscreen',
  'message me: remind me to test Jarvis',
  'start a break',
  'end the break',
  'close the inspector',
  'show the inspector',
  'toggle the inspector',
  'take a pause',
  'take a rest',
] as const;
