import {beforeEach,describe,expect,it,vi} from 'vitest';
import type {RlmChildRequest,RlmBudget} from '@/features/context/rlmRuntime';
import type {ExecutionIdentity} from '@/features/context/gateway/contextGatewayContracts';
const state=vi.hoisted(()=>({inputs:[] as unknown[],native:vi.fn(async(_request:unknown)=>({answer:'native fixture',citations:[]}))}));
vi.mock('@/lib/ai/adapters/codexRlmBoundChild',()=>({createRegisteredCodexRlmChild:()=>state.native}));
vi.mock('@/features/context/rlmRuntime',async importOriginal=>{const actual=await importOriginal<typeof import('@/features/context/rlmRuntime')>();return {...actual,createRlmRuntime:()=>({investigate:async(input:unknown)=>{state.inputs.push(input);return {answer:'runtime fixture',citations:[],trace:{runId:'fixture'}};}})};});
import {createProductionRlmChildRunner,createProductionRlmContextTool} from '@/features/context/contextRlmProduction';
const identity:ExecutionIdentity={transportConnectionId:'openai-codex',transportAdapterId:'codex-app-server',upstreamProviderId:'openai',upstreamModelId:'gpt-6-luna',providerQualifiedModelId:'openai/gpt-6-luna',observedProviderIdentity:'openai/gpt-6-luna',authBillingRoute:'codex-cli-session',effort:'low',fastVariant:'standard',catalogRevision:'sha256:'+'b'.repeat(64)};
function request(overrides:Partial<ExecutionIdentity>={}):RlmChildRequest{return {question:'Find source fact',evidence:[],sourcePointers:[],executionIdentity:{...identity,...overrides},depth:1,budget:{maxInputTokens:100,maxOutputTokens:100},signal:new AbortController().signal};}
function harness(){return {listModels:vi.fn(async()=>[{id:'gpt-6-luna',variants:['low']}]),createSession:vi.fn(async()=>({id:'fixture-child'})),deleteSession:vi.fn(async()=>{}),send:vi.fn(async function*(){yield {type:'assistant.delta' as const,text:'OpenCode fixture'};})};}
beforeEach(()=>{state.inputs=[];state.native.mockReset();state.native.mockResolvedValue({answer:'native fixture',citations:[]});});
describe('production bounded Codex child selection',()=>{
 for(const transportAdapterId of ['codex-cli','codex-app-server'])it(`selects only the registered native ${transportAdapterId} runner and forwards the original request`,async()=>{const oc=harness();const child=createProductionRlmChildRunner(oc as never,state.native);const input=request({transportAdapterId});expect(await child(input)).toEqual({answer:'native fixture',citations:[]});expect(state.native).toHaveBeenCalledWith(input);expect(state.native.mock.calls[0][0]).toBe(input);expect(oc.send).not.toHaveBeenCalled();});
 for(const mismatch of [{transportConnectionId:'other-codex'},{upstreamProviderId:'other-provider'}])it(`retains the unsupported guard for mismatched ${Object.keys(mismatch)[0]}`,async()=>{const oc=harness();await expect(createProductionRlmChildRunner(oc as never,state.native)(request(mismatch))).rejects.toMatchObject({code:'execution_route_unavailable'});expect(state.native).not.toHaveBeenCalled();expect(oc.send).not.toHaveBeenCalled();});
 it('propagates native authority rejection without another harness or ordinary adapter fallback',async()=>{const oc=harness();const failure=new Error('rlm_native_authority_unavailable');state.native.mockRejectedValue(failure);await expect(createProductionRlmChildRunner(oc as never,state.native)(request())).rejects.toBe(failure);expect(oc.send).not.toHaveBeenCalled();});
 it('keeps OpenCode on the original bounded child path',async()=>{const oc=harness();const input=request({transportConnectionId:'opencode-cli',transportAdapterId:'opencode-cli',authBillingRoute:'opencode-provider-session'});expect(await createProductionRlmChildRunner(oc as never,state.native)(input)).toMatchObject({answer:'OpenCode fixture'});expect(state.native).not.toHaveBeenCalled();expect(oc.send).toHaveBeenCalledOnce();});
 for(const codex of [true,false])it(`caps concurrency only for the trusted Codex route, codex=${codex}`,async()=>{const selected=codex?identity:{...identity,transportConnectionId:'opencode-cli',transportAdapterId:'opencode-cli',authBillingRoute:'opencode-provider-session'};const lease={sessionId:'parent',accountId:'account',chatId:'chat',contextRevision:'revision',expiresAt:Date.now()+60000,executionIdentity:selected};await createProductionRlmContextTool().execute({operation:'investigate',query:'Audit every mapped source'},lease as never);const input=state.inputs[0] as {budget:RlmBudget};expect(input.budget.maxConcurrentSubcalls).toBe(codex?1:2);expect(input.budget.maxDepth).toBe(1);expect(input.budget.maxSubcalls).toBe(4);expect(input.budget.maxWallTimeMs).toBe(90000);});
});
