import {describe,expect,it,vi} from 'vitest';
import crypto from 'node:crypto';
import {currentRlmSourceRevision,type RlmRevisionSource,type RlmRevisionStat} from './contextRlmSourceRevision';
import {createRlmTraceStore} from './contextRlmTraceStore';
import type {RlmTerminalReceipt} from './rlmRuntime';
const source:RlmRevisionSource={mapId:'map',nodeId:'node',sourceKind:'file_version',rootDir:'C:/fixture',path:'C:/fixture/source.txt'};
function fixture(){const state={text:'first',size:5,modifiedMs:10};const stat=vi.fn<RlmRevisionStat>(async(path,hash)=>({ok:true,path,kind:'file',size:state.size,createdMs:1,modifiedMs:state.modifiedMs,...(hash?{sha256:('sha256:'+crypto.createHash('sha256').update(state.text).digest('hex')) as `sha256:${string}`}:{})}));return {state,stat};}
describe('actual bounded Context source revision',()=>{
 it('uses actual SHA content changes even when size and timestamps remain identical',async()=>{const f=fixture();const before=await currentRlmSourceRevision([source],f.stat);f.state.text='other';const after=await currentRlmSourceRevision([source],f.stat);expect(before).toMatch(/^sha256:[a-f0-9]{64}$/);expect(after).not.toBe(before);expect(f.stat.mock.calls.map(call=>call[1])).toEqual([false,true,false,false,true,false]);expect(f.stat.mock.calls.every(call=>call[2].strictProjectBoundary===true)).toBe(true);});
 it('does not treat a timestamp-only change as source content revision proof',async()=>{const f=fixture();const before=await currentRlmSourceRevision([source],f.stat);f.state.modifiedMs=20;expect(await currentRlmSourceRevision([source],f.stat)).toBe(before);});
 it('invalidates source removal and identity changes without caller revision arguments',async()=>{const f=fixture();const before=await currentRlmSourceRevision([source],f.stat);expect(await currentRlmSourceRevision([],f.stat)).not.toBe(before);expect(await currentRlmSourceRevision([{...source,nodeId:'replacement'}],f.stat)).not.toBe(before);});
 it('preflights all bytes before any hash begins and denies over-budget source sets',async()=>{const f=fixture();f.state.size=1024*1024;const sources=Array.from({length:9},(_,i)=>({...source,nodeId:String(i)}));expect(await currentRlmSourceRevision(sources,f.stat)).toBeUndefined();expect(f.stat).toHaveBeenCalledTimes(9);expect(f.stat.mock.calls.every(call=>call[1]===false)).toBe(true);});
 it('denies over-count inventory without stat or hash work',async()=>{const f=fixture();expect(await currentRlmSourceRevision(Array.from({length:129},()=>source),f.stat)).toBeUndefined();expect(f.stat).not.toHaveBeenCalled();});
 it('denies unavailable files and malformed native hashes',async()=>{const f=fixture();f.stat.mockResolvedValue({ok:false,path:source.path,error:{code:'not_found'}} as never);expect(await currentRlmSourceRevision([source],f.stat)).toBeUndefined();const g=fixture();g.stat.mockImplementation(async(path,hash)=>({ok:true,path,kind:'file',size:5,createdMs:1,modifiedMs:10,...(hash?{sha256:'invalid' as `sha256:${string}`}:{})}));expect(await currentRlmSourceRevision([source],g.stat)).toBeUndefined();});
 it('denies a size or version race around the native hash',async()=>{const f=fixture();const original=f.stat.getMockImplementation()!;f.stat.mockImplementation(async(path,hash,options)=>{if(hash)f.state.modifiedMs++;return original(path,hash,options);});expect(await currentRlmSourceRevision([source],f.stat)).toBeUndefined();});
 it('honors cancellation before any work or between preflight and hash',async()=>{const f=fixture();const controller=new AbortController();controller.abort();await expect(currentRlmSourceRevision([source],f.stat,controller.signal)).rejects.toThrow();expect(f.stat).not.toHaveBeenCalled();const during=new AbortController();const original=f.stat.getMockImplementation()!;f.stat.mockImplementation(async(path,hash,options)=>{const value=await original(path,hash,options);during.abort();return value;});await expect(currentRlmSourceRevision([source],f.stat,during.signal)).rejects.toThrow();expect(f.stat.mock.calls.every(call=>call[1]===false)).toBe(true);});
 it('hashes trusted inline content and the actual selected Git commit without filesystem work',async()=>{const f=fixture();const git={...source,sourceKind:'git',gitCommit:'a'.repeat(40),inlineContent:'first'};const before=await currentRlmSourceRevision([git],f.stat);expect(await currentRlmSourceRevision([{...git,inlineContent:'other'}],f.stat)).not.toBe(before);expect(await currentRlmSourceRevision([{...git,gitCommit:'b'.repeat(40)}],f.stat)).not.toBe(before);expect(f.stat).not.toHaveBeenCalled();});
 it('denies unsupported federated source kinds and Git without a verified commit before any stat',async()=>{const f=fixture();for(const sourceKind of ['chat_turn','siyuan_block','note','git'])expect(await currentRlmSourceRevision([{...source,sourceKind,inlineContent:'metadata'}],f.stat)).toBeUndefined();expect(f.stat).not.toHaveBeenCalled();});
 it('makes an old receipt unavailable after a current content revision changes in the same chat',async()=>{const f=fixture();const store=createRlmTraceStore();const scope={accountId:'account',workspaceId:'workspace',projectId:'project',worktreeId:'worktree',chatId:'chat',contextRevision:'epoch:'+await currentRlmSourceRevision([source],f.stat)};const terminal={runId:'run',startedAt:1,endedAt:2,status:'failed',trace:{mode:'rlm',runId:'run',wallTimeMs:1,events:[],toolInvocations:[],usage:{toolCalls:0,subcalls:0,openBytes:0,maxDepthReached:0},budgetExhausted:false}} as unknown as RlmTerminalReceipt;expect(store.publish(scope,terminal)).toBe(true);expect(store.lookup(scope,'run')).toBeDefined();f.state.text='other';expect(store.lookup({...scope,contextRevision:'epoch:'+await currentRlmSourceRevision([source],f.stat)},'run')).toBeUndefined();});
});
