import { describe, expect, it, vi } from 'vitest';
import { createRlmOpenCodeTool, type RlmContextLease } from './rlmOpenCodeTool';
const lease={sessionId:'session',accountId:'account',workspaceId:'workspace',projectId:'project',worktreeId:'worktree',chatId:'chat',contextRevision:'revision',expiresAt:2000};
function fixture(){return {now:()=>1000,queryService:Object.fromEntries(['describe','search','open','expand','related','timeline','sources','checkpoint'].map(name=>[name,vi.fn(async()=>({items:[]}))])) as any,rlmRuntime:{investigate:vi.fn(async(_input:unknown,_lease?:Readonly<RlmContextLease>)=>({trace:{runId:'run'}}))},traceLookup:vi.fn(async(_runId:string,_lease:Readonly<RlmContextLease>,_signal?:AbortSignal)=>({runId:'run'}))};}
describe('trusted trace lookup operation',()=>{
 it('passes only the exact ID and an immutable captured lease, never launches a child',async()=>{const f=fixture();const tool=createRlmOpenCodeTool(f);expect(await tool.execute({operation:'trace',runId:'run'},lease)).toEqual({found:true,receipt:{runId:'run'}});const [id,scope]=f.traceLookup.mock.calls[0];expect(id).toBe('run');expect(scope).toEqual(lease);expect(scope).not.toBe(lease);expect(Object.isFrozen(scope)).toBe(true);expect(f.rlmRuntime.investigate).not.toHaveBeenCalled();expect(f.queryService.search).not.toHaveBeenCalled();});
 it.each(['accountId','workspaceId','projectId','worktreeId','chatId','contextRevision','query'])('rejects provider authority or unrelated %s arguments',async key=>{const f=fixture();await expect(createRlmOpenCodeTool(f).execute({operation:'trace',runId:'run',[key]:'override'},lease)).rejects.toMatchObject({code:'invalid_arguments'});expect(f.traceLookup).not.toHaveBeenCalled();});
 it.each(['',' run','run ','x'.repeat(513),'run\0id'])('rejects malformed exact run IDs',async runId=>{const f=fixture();await expect(createRlmOpenCodeTool(f).execute({operation:'trace',runId},lease)).rejects.toMatchObject({code:'invalid_arguments'});expect(f.traceLookup).not.toHaveBeenCalled();});
 it('uses the same not-found envelope when unavailable or unknown',async()=>{const f=fixture();f.traceLookup.mockResolvedValue(undefined as any);expect(await createRlmOpenCodeTool(f).execute({operation:'trace',runId:'unknown'},lease)).toEqual({found:false});expect(await createRlmOpenCodeTool({...f,traceLookup:undefined}).execute({operation:'trace',runId:'unknown'},lease)).toEqual({found:false});});
 it('rejects expired authority before lookup',async()=>{const f=fixture();await expect(createRlmOpenCodeTool(f).execute({operation:'trace',runId:'run'},{...lease,expiresAt:999})).rejects.toMatchObject({code:'lease_expired'});expect(f.traceLookup).not.toHaveBeenCalled();});
 it('honors cancellation before and after asynchronous lookup',async()=>{const f=fixture();const controller=new AbortController();controller.abort();await expect(createRlmOpenCodeTool(f).execute({operation:'trace',runId:'run'},lease,controller.signal)).rejects.toThrow();expect(f.traceLookup).not.toHaveBeenCalled();const during=new AbortController();f.traceLookup.mockImplementation(async()=>{during.abort();return {runId:'run'};});await expect(createRlmOpenCodeTool(f).execute({operation:'trace',runId:'run'},lease,during.signal)).rejects.toThrow();});
 it('passes the captured originating lease as an internal second investigation argument',async()=>{const f=fixture();const identity={transportConnectionId:'oc',transportAdapterId:'opencode-cli',upstreamProviderId:'openai',upstreamModelId:'gpt-6-luna',providerQualifiedModelId:'openai/gpt-6-luna',authBillingRoute:'opencode-provider-session',effort:'low',fastVariant:'standard',catalogRevision:'sha256:'+'b'.repeat(64)};const trusted={...lease,executionIdentity:identity};await createRlmOpenCodeTool(f).execute({operation:'investigate',query:'Audit every record'},trusted as any);expect(f.rlmRuntime.investigate).toHaveBeenCalledOnce();const [,captured]=f.rlmRuntime.investigate.mock.calls[0] as any;expect(captured).toEqual(trusted);expect(Object.isFrozen(captured.executionIdentity)).toBe(true);trusted.chatId='changed';identity.effort='high';expect(captured.chatId).toBe('chat');expect(captured.executionIdentity.effort).toBe('low');});
});
