import {beforeEach,it,expect,vi} from 'vitest';
const live=vi.hoisted(()=>({account:'account',auth:{workspaceId:'workspace',projectId:'project',chatModelSelection:{mode:'none' as const}},chat:vi.fn(),event:vi.fn(),updateChat:vi.fn(),updateEvent:vi.fn(),createEvent:vi.fn()}));
vi.mock('@/stores/auth',()=>({useAuthStore:{getState:()=>live.auth}}));
vi.mock('@/lib/accountIdentity',async importOriginal=>({...await importOriginal<any>(),getActiveAccountIdentity:()=>({accountId:live.account})}));
vi.mock('@/lib/db/repositories',async importOriginal=>({...await importOriginal<any>(),chatRepo:{getById:live.chat,update:live.updateChat},eventRepo:{getById:live.event,update:live.updateEvent,create:live.createEvent}}));
import {runAction} from '@/lib/actions/runner';
import {getBuiltinAction} from '@/lib/actions/registry';
const context={source:'ai' as const,accountId:'account',runId:'run',approvalId:'approval',requestId:'request',chatId:'caller'};
beforeEach(()=>{live.createEvent.mockReset().mockResolvedValue({id:'evt_new',title:'Future',status:'scheduled',source_ref:{}});live.account='account';live.auth={workspaceId:'workspace',projectId:'project',chatModelSelection:{mode:'none' as const}};live.chat.mockReset().mockResolvedValue({id:'cht_own',workspace_id:'workspace',project_id:'project'});live.event.mockReset().mockResolvedValue({id:'evt_own',workspace_id:'workspace',project_id:'project'});live.updateChat.mockReset().mockResolvedValue({id:'cht_own'});live.updateEvent.mockReset().mockResolvedValue({id:'evt_own',title:'Preview',status:'cancelled',source_ref:{}});});
it.each([['chat.rename',{chatId:'cht_own',title:'Renamed'}],['schedule.pause',{eventId:'evt_own'}]] as const)('existing public runner refuses %s without issued approval',async(id,params)=>{expect(await runAction(id,params,{source:'ai',chatId:'caller',accountId:'account'},{emitToast:false})).toMatchObject({ok:false});expect(live.updateChat).not.toHaveBeenCalled();expect(live.updateEvent).not.toHaveBeenCalled();});
it('real registered rename executor persists owned target only after scope guard',async()=>{expect(await getBuiltinAction('chat.rename')!.run({chatId:'cht_own',title:'Renamed'},context)).toMatchObject({ok:true});expect(live.updateChat).toHaveBeenCalledExactlyOnceWith('cht_own',{title:'Renamed'});});
it('real registered pause executor preserves history through cancelled status',async()=>{expect(await getBuiltinAction('schedule.pause')!.run({eventId:'evt_own'},context)).toMatchObject({ok:true});expect(live.updateEvent).toHaveBeenCalledExactlyOnceWith('evt_own',{status:'cancelled'});});
it.each(['chat.rename','schedule.pause'])('real %s executor refuses foreign project before mutation',async id=>{live.auth.projectId='foreign';await expect(getBuiltinAction(id)!.run(id==='chat.rename'?{chatId:'cht_own',title:'Renamed'}:{eventId:'evt_own'},context)).rejects.toThrow();expect(live.updateChat).not.toHaveBeenCalled();expect(live.updateEvent).not.toHaveBeenCalled();});
it('real rename executor refuses account change during target read',async()=>{live.chat.mockImplementation(async()=>{live.account='other';return {id:'cht_own',workspace_id:'workspace',project_id:'project'};});await expect(getBuiltinAction('chat.rename')!.run({chatId:'cht_own',title:'Renamed'},context)).rejects.toThrow();expect(live.updateChat).not.toHaveBeenCalled();});

it('real schedule create refuses caller from another project before write',async()=>{live.chat.mockResolvedValue({id:'caller',workspace_id:'workspace',project_id:'original-project'});await expect(getBuiltinAction('schedule.create')!.run({title:'Future',prompt:'Preview',startAtMs:Date.now()+86400000,recurrence:'once'},context)).rejects.toThrow(/outside/);expect(live.createEvent).not.toHaveBeenCalled();});
it('real schedule create persists original scoped project after approval',async()=>{expect(await getBuiltinAction('schedule.create')!.run({title:'Future',prompt:'Preview',startAtMs:Date.now()+86400000,recurrence:'once'},context)).toMatchObject({ok:true});expect(live.createEvent).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({workspace_id:'workspace',project_id:'project'}));});
