import * as React from 'react';
import { Activity, GitCompareArrows, MessageSquareMore, Rocket, ShieldCheck } from 'lucide-react';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import type { EvaluationRun, ModelVersion, ProjectSnapshot } from './domain';
import type { FoundryDeploymentRecord } from './deployment';

export function EvaluationArenaPanel({ candidate, evaluation, championVersionId, onEvaluate, onPromote }: { candidate?: ModelVersion; evaluation?: EvaluationRun; championVersionId?: string; onEvaluate: () => void; onPromote: () => void }) {
  if (!candidate) return null;
  return <Card className="overflow-hidden border-violet-500/25 bg-panel/90"><CardHeader className="border-b border-border bg-gradient-to-r from-violet-500/10 via-transparent to-cyan-500/10"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-1 flex items-center gap-2 text-metadata uppercase tracking-[0.16em] text-violet-300"><GitCompareArrows className="h-4 w-4" /> Evaluation Arena</div><CardTitle>Candidate against the gates</CardTitle><CardDescription>Deterministic quality, regression, safety, and hidden-case evidence decide promotion.</CardDescription></div>{evaluation && <Badge variant="outline" className={evaluation.gate.result === 'pass' ? 'border-emerald-500/40 text-emerald-300' : 'border-amber-500/40 text-amber-300'}>{evaluation.gate.result}</Badge>}</div></CardHeader><CardContent className="space-y-4 pt-4">{evaluation ? <><div className="grid gap-3 md:grid-cols-3"><Metric label="Cases" value={`${evaluation.caseEvidence.length}`} detail="Evidence captured" /><Metric label="Safety" value={`${evaluation.safetyFailures.length}`} detail="Failures" danger={evaluation.safetyFailures.length > 0} /><Metric label="Gate" value={evaluation.gate.result.toUpperCase()} detail={evaluation.gate.reasons.length ? evaluation.gate.reasons.join(', ') : 'Every threshold passed'} /></div><div className="overflow-hidden rounded-lg border"><table className="w-full text-left text-secondary"><thead className="bg-muted/40 text-metadata uppercase tracking-wide text-muted-foreground"><tr><th className="px-3 py-2">Metric</th><th className="px-3 py-2">Base</th><th className="px-3 py-2">Candidate</th><th className="px-3 py-2">Delta</th></tr></thead><tbody>{evaluation.aggregateDeltas.map((metric) => <tr key={metric.metricId} className="border-t border-border"><td className="px-3 py-2 text-ui-strong">{metric.metricId}</td><td className="px-3 py-2">{metric.baseValue.toFixed(3)}</td><td className="px-3 py-2">{metric.candidateValue.toFixed(3)}</td><td className={metric.passes ? 'px-3 py-2 text-emerald-300' : 'px-3 py-2 text-destructive'}>{metric.candidateDeltaFromBase >= 0 ? '+' : ''}{metric.candidateDeltaFromBase.toFixed(3)}</td></tr>)}</tbody></table></div></> : <div className="rounded-lg border border-dashed p-4 text-secondary text-muted-foreground">No evidence has been produced for this candidate yet.</div>}<div className="flex flex-wrap gap-2">{!evaluation && <Button variant="accent" onClick={onEvaluate}>Run fixture evaluation</Button>}{evaluation?.gate.result === 'pass' && !championVersionId && <Button variant="accent" onClick={onPromote}><ShieldCheck className="h-4 w-4" /> Promote candidate</Button>}{championVersionId && <Badge className="bg-emerald-500/15 text-emerald-300">Current champion</Badge>}</div></CardContent></Card>;
}

export function FixtureEvaluationEvidencePanel({ evaluation }: { evaluation?: EvaluationRun }) {
  if (!evaluation) return null;
  return <details className="rounded-lg border border-violet-500/20 bg-background/30 p-3"><summary className="cursor-pointer text-secondary text-ui-strong">Per-case evaluation evidence</summary><div className="mt-3 overflow-hidden rounded-md border"><table className="w-full text-left text-metadata"><thead className="bg-muted/40 text-muted-foreground"><tr><th className="px-2 py-1.5">Case</th><th className="px-2 py-1.5">Visibility</th><th className="px-2 py-1.5">Safety</th><th className="px-2 py-1.5">Evidence</th></tr></thead><tbody>{evaluation.caseEvidence.map((caseEvidence) => <tr key={caseEvidence.caseId} className="border-t border-border"><td className="px-2 py-1.5">{caseEvidence.hidden ? 'Hidden case' : caseEvidence.caseId}</td><td className="px-2 py-1.5">{caseEvidence.hidden ? 'Hidden' : 'Visible'}</td><td className={caseEvidence.safetyFailures.length ? 'px-2 py-1.5 text-destructive' : 'px-2 py-1.5 text-emerald-300'}>{caseEvidence.safetyFailures.length ? caseEvidence.safetyFailures.join(', ') : 'Passed'}</td><td className="px-2 py-1.5 font-mono text-muted-foreground">{caseEvidence.evidenceHash.slice(0, 12)}…</td></tr>)}</tbody></table></div><p className="mt-2 text-metadata text-muted-foreground">Inputs and outputs are intentionally not persisted in fixture evaluation evidence.</p></details>;
}

function Metric({ label, value, detail, danger = false }: { label: string; value: string; detail: string; danger?: boolean }) {
  return <div className="rounded-lg border bg-background/40 p-3"><div className="text-metadata uppercase tracking-[0.14em] text-muted-foreground">{label}</div><div className={danger ? 'mt-1 text-xl font-semibold text-destructive' : 'mt-1 text-xl font-semibold text-foreground'}>{value}</div><div className="text-metadata text-muted-foreground">{detail}</div></div>;
}

export function DeploymentPanel({ snapshot, deployment, routingMode, trafficPercent, onRoutingMode, onTrafficPercent, onActivate, onPause }: { snapshot: ProjectSnapshot; deployment: FoundryDeploymentRecord | null; routingMode: FoundryDeploymentRecord['routingMode']; trafficPercent: number; onRoutingMode: (mode: FoundryDeploymentRecord['routingMode']) => void; onTrafficPercent: (value: number) => void; onActivate: () => void; onPause: () => void }) {
  if (!snapshot.championVersionId) return null;
  return <Card className="border-cyan-500/25"><CardHeader><div className="flex items-start justify-between gap-3"><div><div className="mb-1 flex items-center gap-2 text-metadata uppercase tracking-[0.16em] text-cyan-300"><Rocket className="h-4 w-4" /> Local deployment</div><CardTitle>Route to the champion</CardTitle><CardDescription>Activation is explicit, reversible, and limited to the verified local champion.</CardDescription></div><Badge variant="outline" className={deployment?.status === 'active' ? 'border-emerald-500/40 text-emerald-300' : ''}>{deployment?.status ?? 'inactive'}</Badge></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><label className="space-y-1 text-secondary"><span className="text-metadata text-muted-foreground">Routing mode</span><select value={routingMode} onChange={(event) => onRoutingMode(event.target.value as FoundryDeploymentRecord['routingMode'])} className="h-9 w-full rounded-md border border-input bg-background px-3"><option value="manual">Manual model picker</option><option value="specialist_default">Specialist default</option><option value="shadow">Shadow only</option></select></label><label className="space-y-1 text-secondary"><span className="text-metadata text-muted-foreground">Traffic: {trafficPercent}%</span><input type="range" min={0} max={100} step={5} value={trafficPercent} onChange={(event) => onTrafficPercent(Number(event.target.value))} className="h-9 w-full accent-cyan-400" /></label></div><div className="flex flex-wrap gap-2">{deployment?.status === 'active' ? <Button variant="outline" onClick={onPause}>Pause deployment</Button> : <Button variant="accent" onClick={onActivate}>Activate local champion</Button>}</div><p className="text-metadata text-muted-foreground"><Activity className="mr-1 inline h-3.5 w-3.5" /> Shadow mode records routing intent without replacing the current answer path. Promotion evidence remains immutable.</p></CardContent></Card>;
}

export function ImprovementPanel({ feedbackCount, cycleCount, consentApproved, onConsent, onFeedback, onCycle }: { feedbackCount: number; cycleCount: number; consentApproved: boolean; onConsent: (approved: boolean) => void; onFeedback: (rating: 'helpful' | 'not_helpful') => void; onCycle: () => void }) {
  return <Card><CardHeader><div className="flex items-center gap-2"><MessageSquareMore className="h-5 w-5 text-violet-300" /><CardTitle>Controlled improvement</CardTitle></div><CardDescription>Only consented evidence can enter a new dataset or improvement cycle.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><Metric label="Approved feedback" value={`${feedbackCount}`} detail="Local evidence events" /><Metric label="Improvement cycles" value={`${cycleCount}`} detail="Provenance-linked cycles" /></div><label className="flex items-start gap-2 text-secondary"><input type="checkbox" checked={consentApproved} onChange={(event) => onConsent(event.target.checked)} className="mt-0.5" /><span>I consent to using this evaluation evidence for local improvement of this specialist.</span></label><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={!consentApproved} onClick={() => onFeedback('helpful')}>Mark helpful</Button><Button variant="outline" disabled={!consentApproved} onClick={() => onFeedback('not_helpful')}>Mark not helpful</Button><Button variant="accent" disabled={!feedbackCount} onClick={onCycle}>Create improvement cycle</Button></div></CardContent></Card>;
}
