import { Archive, Cpu, RotateCcw } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import type { LocalAdapterRecord } from './adapterRegistry';

export function RealAdapterRegistryPanel({ records, runtimeReady, onUse, onProbe, onEvaluate, onPromote, onArchive }: { records: readonly LocalAdapterRecord[]; runtimeReady: boolean; onUse: (record: LocalAdapterRecord) => void; onProbe: (record: LocalAdapterRecord) => void; onEvaluate: (record: LocalAdapterRecord) => void; onPromote: (record: LocalAdapterRecord) => void; onArchive: (record: LocalAdapterRecord) => void }) {
  if (!records.length) return null;
  return <Card className="border-emerald-500/25"><CardHeader><CardTitle className="flex items-center gap-2"><Cpu className="h-5 w-5 text-emerald-300" /> Local adapter registry</CardTitle><CardDescription>Evaluation is local and mandatory. Only a manually approved passing adapter can route chats.</CardDescription></CardHeader><CardContent className="space-y-3">{records.map((record) => { const evaluated = record.evaluation?.artifactManifestSha256 === record.artifactManifestSha256; const report = evaluated ? record.evaluation?.report : undefined; const passing = report?.gate === 'pass'; const rollbackAvailable = record.status === 'promoted' && Boolean(record.previousChampionJobId); return <div key={record.jobId} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-mono text-metadata">{record.jobId} · {record.artifactManifestSha256.slice(0, 12)}…</div><div className="mt-1 text-metadata text-muted-foreground">{record.status === 'promoted' ? rollbackAvailable ? 'Champion · prior verified champion retained' : 'Champion' : record.status === 'archived' ? 'Archived' : !evaluated ? 'Needs evaluation' : passing ? `Passed: ${report!.candidateScore.toFixed(3)} (${report!.delta >= 0 ? '+' : ''}${report!.delta.toFixed(3)} vs base)` : 'Blocked by evaluation gate'}</div></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={!runtimeReady || record.status === 'archived'} onClick={() => onProbe(record)}>Probe</Button><Button variant="outline" disabled={!runtimeReady || record.status === 'archived'} onClick={() => onEvaluate(record)}>Evaluate</Button><Button variant="accent" disabled={!passing || record.status === 'promoted'} onClick={() => onPromote(record)}>{record.status === 'promoted' ? 'Champion' : 'Approve & promote'}</Button>{rollbackAvailable && <Button variant="outline" onClick={() => window.dispatchEvent(new CustomEvent('vibespace:foundry-rollback-requested', { detail: { projectId: record.projectId } }))}><RotateCcw className="h-4 w-4" /> Roll back</Button>}<Button variant="accent" disabled={!runtimeReady || record.status !== 'promoted'} onClick={() => onUse(record)}>Use in chat</Button><Button variant="outline" aria-label={`Archive adapter ${record.jobId}`} disabled={record.status === 'promoted'} onClick={() => onArchive(record)}><Archive className="h-4 w-4" /></Button></div></div>{report && <EvaluationEvidence report={report} />}</div>; })}</CardContent></Card>;
}

function EvaluationEvidence({ report }: { report: NonNullable<LocalAdapterRecord['evaluation']>['report'] }) {
  return <details className="mt-3 rounded-md border border-border bg-background/40 p-3"><summary className="cursor-pointer text-secondary text-ui-strong">Evaluation Arena · {report.suite} · {report.caseCount} local case{report.caseCount === 1 ? '' : 's'}</summary><div className="mt-3 grid gap-2 sm:grid-cols-4"><Score label="Base" value={report.baseScore} /><Score label="Candidate" value={report.candidateScore} positive /><Score label="Champion" value={report.championScore} /><Score label="Gate" value={report.gate === 'pass' ? 1 : 0} text={report.gate === 'pass' ? 'Pass' : 'Blocked'} positive={report.gate === 'pass'} /></div><div className="mt-3 overflow-hidden rounded-md border"><table className="w-full text-left text-metadata"><thead className="bg-muted/40 text-muted-foreground"><tr><th className="px-2 py-1.5">Case</th><th className="px-2 py-1.5">Base</th><th className="px-2 py-1.5">Candidate</th><th className="px-2 py-1.5">Champion</th><th className="px-2 py-1.5">Evidence</th></tr></thead><tbody>{report.caseEvidence.map((caseEvidence) => <tr key={caseEvidence.caseId} className="border-t border-border"><td className="px-2 py-1.5">{caseEvidence.hidden ? 'Hidden case' : caseEvidence.caseId}</td><td className="px-2 py-1.5">{caseEvidence.baseScore.toFixed(3)}</td><td className={caseEvidence.candidateScore >= caseEvidence.baseScore ? 'px-2 py-1.5 text-emerald-300' : 'px-2 py-1.5 text-destructive'}>{caseEvidence.candidateScore.toFixed(3)}</td><td className="px-2 py-1.5">{caseEvidence.championScore === null ? '—' : caseEvidence.championScore.toFixed(3)}</td><td className="px-2 py-1.5 font-mono text-muted-foreground">{caseEvidence.evidenceHash.slice(0, 12)}…</td></tr>)}</tbody></table></div><p className={report.safetyFailures.length ? 'mt-3 text-metadata text-destructive' : 'mt-3 text-metadata text-emerald-300'}>{report.safetyFailures.length ? `Safety gate blocked: ${report.safetyFailures.join('; ')}` : 'Safety gate passed. Prompts and generated outputs remain local; this view stores hashes and aggregate scores only.'}</p></details>;
}

function Score({ label, value, text, positive = false }: { label: string; value: number | null; text?: string; positive?: boolean }) {
  return <div className="rounded border border-border px-2 py-1.5"><div className="text-metadata uppercase tracking-wide text-muted-foreground">{label}</div><div className={positive ? 'text-secondary text-emerald-300' : 'text-secondary'}>{text ?? (value === null ? '—' : value.toFixed(3))}</div></div>;
}
