export const COMMANDS = Object.freeze([
  {
    id: 'terminal.open',
    family: 'terminal',
    actions: ['open'],
    aliases: [
      'open terminal',
      'open a terminal',
      'launch terminal',
      'start terminal',
      'new terminal',
      'open claude terminal',
      'open codex terminal',
      'open opencode terminal',
    ],
    specificity: 50,
  },
  {
    id: 'appearance.background.set',
    family: 'background',
    actions: ['set'],
    aliases: [
      'change background',
      'set background',
      'make background',
      'change the background',
      'set the background',
      'make the background',
    ],
    specificity: 50,
  },
  {
    id: 'button.rename',
    family: 'button',
    actions: ['rename'],
    aliases: [
      'rename button',
      'rename the button',
      'change button text',
      'change the button text',
      'set button label',
      'set the button label',
    ],
    specificity: 60,
  },
  {
    id: 'panel.open',
    family: 'panel',
    actions: ['open'],
    aliases: ['open panel', 'open side panel', 'open sidebar'],
    specificity: 60,
  },
  {
    id: 'panel.close',
    family: 'panel',
    actions: ['close'],
    aliases: ['close panel', 'close side panel', 'close sidebar'],
    specificity: 60,
  },
  {
    id: 'panel.toggle',
    family: 'panel',
    actions: ['toggle'],
    aliases: ['toggle panel', 'toggle side panel', 'toggle sidebar'],
    specificity: 60,
  },
  {
    id: 'status.show',
    family: 'status',
    actions: ['show'],
    aliases: ['show status', 'show router status', 'display status', 'display router status'],
    specificity: 60,
  },
  {
    id: 'font.adjust',
    family: 'font',
    actions: ['increase', 'decrease'],
    aliases: [
      'increase font size',
      'decrease font size',
      'make text bigger',
      'make text smaller',
      'bigger text',
      'smaller text',
    ],
    specificity: 55,
  },
  {
    id: 'music.play',
    family: 'music',
    actions: ['play'],
    aliases: ['play music', 'start music'],
    specificity: 55,
  },
  {
    id: 'music.pause',
    family: 'music',
    actions: ['pause'],
    aliases: ['pause music'],
    specificity: 55,
  },
  {
    id: 'page.open',
    family: 'page',
    actions: ['open'],
    aliases: [
      'open settings',
      'open chat',
      'open terminal page',
      'open tools',
      'open files',
      'open schedule',
      'open calendar',
      'go to settings',
      'go to chat',
      'go to tools',
      'go to files',
    ],
    specificity: 45,
  },
]);

export const DIRECT_COMMANDS = Object.freeze([
  { id: 'terminal.list', aliases: ['list terminals'], slot: 'none' },
  { id: 'terminal.status', aliases: ['show terminal status'], slot: 'none' },
  { id: 'terminal.focus', aliases: ['focus terminal'], slot: 'remainder', slotKey: 'target' },
  { id: 'terminal.split', aliases: ['split terminal'], slot: 'optional_remainder', slotKey: 'target' },
  { id: 'terminal.rename', aliases: ['rename terminal'], slot: 'remainder', slotKey: 'target' },
  { id: 'terminal.restart', aliases: ['restart terminal'], slot: 'remainder', slotKey: 'target' },
  { id: 'terminal.clear', aliases: ['clear terminal'], slot: 'remainder', slotKey: 'target' },
  { id: 'terminal.stop', aliases: ['stop terminal'], slot: 'remainder', slotKey: 'target' },
  { id: 'terminal.close', aliases: ['close terminal'], slot: 'remainder', slotKey: 'target' },
  { id: 'terminal.cancel_queued', aliases: ['cancel queued command'], slot: 'optional_remainder', slotKey: 'target' },

  { id: 'agent.open', aliases: ['open agent cli'], slot: 'remainder', slotKey: 'agent' },
  { id: 'agent.create', aliases: ['create agent'], slot: 'remainder', slotKey: 'agent' },
  { id: 'agent.configure', aliases: ['configure agent'], slot: 'remainder', slotKey: 'agent' },
  { id: 'agent.select', aliases: ['select agent'], slot: 'remainder', slotKey: 'agent' },
  { id: 'agent.status', aliases: ['show agent status'], slot: 'optional_remainder', slotKey: 'agent' },
  { id: 'agent.stop', aliases: ['stop agent'], slot: 'remainder', slotKey: 'agent' },

  { id: 'project.open', aliases: ['open project'], slot: 'remainder', slotKey: 'project' },
  { id: 'project.create', aliases: ['create project'], slot: 'remainder', slotKey: 'project' },
  { id: 'project.switch', aliases: ['switch project'], slot: 'remainder', slotKey: 'project' },
  { id: 'project.settings', aliases: ['open project settings'], slot: 'remainder', slotKey: 'project' },
  { id: 'project.archive', aliases: ['archive project'], slot: 'remainder', slotKey: 'project' },

  { id: 'chat.new', aliases: ['new chat', 'create new chat'], slot: 'none' },
  { id: 'chat.open', aliases: ['open named chat', 'open chat named'], slot: 'remainder', slotKey: 'chat' },
  { id: 'chat.rename', aliases: ['rename chat'], slot: 'remainder', slotKey: 'chat' },
  { id: 'chat.list', aliases: ['list chats'], slot: 'none' },
  { id: 'chat.delete', aliases: ['delete chat'], slot: 'remainder', slotKey: 'chat' },

  { id: 'schedule.create', aliases: ['create schedule', 'make schedule'], slot: 'remainder', slotKey: 'schedule' },
  { id: 'schedule.list', aliases: ['list my schedules', 'list schedules'], slot: 'none' },
  { id: 'schedule.open', aliases: ['open named schedule'], slot: 'remainder', slotKey: 'schedule' },
  { id: 'schedule.pause', aliases: ['pause schedule'], slot: 'remainder', slotKey: 'schedule' },
  { id: 'schedule.resume', aliases: ['resume schedule'], slot: 'remainder', slotKey: 'schedule' },
  { id: 'schedule.enable', aliases: ['enable schedule'], slot: 'remainder', slotKey: 'schedule' },
  { id: 'schedule.disable', aliases: ['disable schedule', 'turn off schedule'], slot: 'remainder', slotKey: 'schedule' },
  { id: 'schedule.run_now', aliases: ['run schedule'], slot: 'remainder', slotKey: 'schedule' },
  { id: 'schedule.edit', aliases: ['edit schedule', 'change schedule'], slot: 'remainder', slotKey: 'schedule' },
  { id: 'schedule.delete', aliases: ['delete schedule'], slot: 'remainder', slotKey: 'schedule' },
  { id: 'timer.start', aliases: ['start timer'], slot: 'remainder', slotKey: 'spec' },
  { id: 'timer.cancel', aliases: ['cancel timer'], slot: 'optional_remainder', slotKey: 'spec' },
  { id: 'alarm.set', aliases: ['set alarm'], slot: 'remainder', slotKey: 'spec' },
  { id: 'alarm.cancel', aliases: ['cancel alarm'], slot: 'optional_remainder', slotKey: 'spec' },

  { id: 'setting.read', aliases: ['read setting'], slot: 'remainder', slotKey: 'setting' },
  { id: 'setting.set', aliases: ['set setting'], slot: 'remainder', slotKey: 'setting' },
  { id: 'setting.toggle', aliases: ['toggle setting'], slot: 'remainder', slotKey: 'setting' },

  { id: 'music.resume', aliases: ['resume music', 'resume the music'], slot: 'none' },
  { id: 'music.stop', aliases: ['stop music', 'stop the music'], slot: 'none' },
  { id: 'music.next', aliases: ['next song'], slot: 'none' },
  { id: 'music.previous', aliases: ['previous song'], slot: 'none' },
  { id: 'music.track', aliases: ['change song'], slot: 'remainder', slotKey: 'text' },
  { id: 'music.volume', aliases: ['set music volume'], slot: 'number', slotKey: 'value' },
  { id: 'music.mute', aliases: ['mute music'], slot: 'none' },
  { id: 'music.unmute', aliases: ['unmute music'], slot: 'none' },

  { id: 'tool.open', aliases: ['open tool'], slot: 'remainder', slotKey: 'tool' },
  { id: 'tool.run', aliases: ['run tool'], slot: 'remainder', slotKey: 'tool' },
  { id: 'tool.stop', aliases: ['stop tool'], slot: 'remainder', slotKey: 'tool' },
  { id: 'skill.open', aliases: ['open skill'], slot: 'remainder', slotKey: 'skill' },
  { id: 'skill.enable', aliases: ['enable skill'], slot: 'remainder', slotKey: 'skill' },
  { id: 'skill.disable', aliases: ['disable skill'], slot: 'remainder', slotKey: 'skill' },
  { id: 'plugin.open', aliases: ['open plugin'], slot: 'remainder', slotKey: 'plugin' },
  { id: 'plugin.connect', aliases: ['connect plugin'], slot: 'remainder', slotKey: 'plugin' },
  { id: 'plugin.disconnect', aliases: ['disconnect plugin'], slot: 'remainder', slotKey: 'plugin' },
  { id: 'plugin.status', aliases: ['show plugin status'], slot: 'optional_remainder', slotKey: 'plugin' },

  { id: 'files.search', aliases: ['search files'], slot: 'remainder', slotKey: 'query' },
  { id: 'file.reveal', aliases: ['reveal file'], slot: 'remainder', slotKey: 'path' },
  { id: 'file.open', aliases: ['open file'], slot: 'remainder', slotKey: 'path' },
  { id: 'context.open', aliases: ['open context item'], slot: 'remainder', slotKey: 'target' },
  { id: 'context.map.create', aliases: ['create context map'], slot: 'optional_remainder', slotKey: 'name' },
  { id: 'context.map.recenter', aliases: ['recenter context map'], slot: 'none' },

  { id: 'task.create', aliases: ['create task'], slot: 'remainder', slotKey: 'task' },
  { id: 'task.open', aliases: ['open task'], slot: 'remainder', slotKey: 'task' },
  { id: 'task.complete', aliases: ['complete task'], slot: 'remainder', slotKey: 'task' },
  { id: 'task.reopen', aliases: ['reopen task'], slot: 'remainder', slotKey: 'task' },
  { id: 'task.assign', aliases: ['assign task'], slot: 'remainder', slotKey: 'assignment' },

  { id: 'workbench.open', aliases: ['open named workbench'], slot: 'remainder', slotKey: 'workbench' },
  { id: 'workbench.template', aliases: ['apply workbench template'], slot: 'remainder', slotKey: 'template' },
  { id: 'workbench.panel.add', aliases: ['add workbench panel'], slot: 'remainder', slotKey: 'panel' },
  { id: 'workbench.wallpaper.set', aliases: ['set workbench wallpaper'], slot: 'remainder', slotKey: 'wallpaper' },
  { id: 'workbench.wallpaper.pause', aliases: ['pause workbench wallpaper'], slot: 'none' },
  { id: 'workbench.wallpaper.resume', aliases: ['resume workbench wallpaper'], slot: 'none' },
]);

export const ACTION_SYNONYMS = Object.freeze({
  open: [
    'open', 'launch', 'start', 'bring up', 'fire up', 'spin up', 'pull up',
    'pop open', 'boot', 'spawn', 'get running', 'bring me', 'go to', 'navigate to', 'switch to',
  ],
  close: ['close', 'shut', 'hide', 'dismiss'],
  toggle: ['toggle', 'flip', 'switch'],
  set: ['set', 'change', 'make', 'switch', 'turn', 'paint'],
  rename: ['rename', 'relabel', 'change', 'set'],
  show: ['show', 'display', 'reveal'],
  increase: ['increase', 'enlarge', 'boost', 'raise', 'bigger', 'larger'],
  decrease: ['decrease', 'shrink', 'lower', 'smaller', 'reduce'],
  play: ['play', 'start'],
  pause: ['pause', 'halt'],
  message: ['message', 'tell', 'ask'],
});

export const FAMILY_TERMS = Object.freeze({
  terminal: [
    'terminal', 'terminals', 'shell', 'shells', 'console', 'consoles',
    'command prompt', 'command window', 'cli', 'coding shell', 'coding console',
    'coding terminal',
  ],
  background: ['background', 'backdrop', 'page color', 'canvas color'],
  button: ['button', 'action button', 'demo button', 'button label', 'button text'],
  panel: ['panel', 'side panel', 'sidebar', 'drawer'],
  status: ['status', 'router status', 'diagnostics', 'diagnostic status'],
  font: ['font', 'font size', 'text size', 'text'],
  music: ['music', 'song', 'audio', 'track'],
  page: ['page', 'screen', 'view', 'settings', 'chat', 'tools', 'files', 'schedule', 'calendar'],
});

export const PROVIDER_ALIASES = Object.freeze({
  claude: [
    'claude', 'claude code', 'cloude', 'anthropic', 'anthropic cli',
    'anthropic coding shell', 'anthropic coding console', 'anthropic coder',
  ],
  codex: [
    'codex', 'openai codex', 'open ai codex', 'openai cli',
    'openai coding console', 'openai coding shell', 'openai coder',
  ],
  opencode: ['opencode', 'open code', 'opencode cli', 'open code cli'],
  copilot: ['copilot', 'github copilot', 'github copilot cli'],
  gemini: ['gemini', 'gemini cli', 'google gemini'],
  grok: ['grok', 'grok build', 'xai grok'],
  qwen: ['qwen', 'qwen code'],
  kiro: ['kiro', 'kiro cli'],
  aider: ['aider'],
  cursor: ['cursor'],
  gpt: ['gpt', 'openai gpt'],
});

export const COLOR_ALIASES = Object.freeze({
  green: ['green', 'lime'],
  purple: ['purple', 'purpel', 'violet'],
  blue: ['blue', 'navy'],
  red: ['red', 'crimson'],
  dark: ['dark', 'black', 'night'],
  light: ['light', 'white', 'bright'],
});

export const PAGE_ALIASES = Object.freeze({
  settings: ['settings', 'preferences', 'options'],
  chat: ['chat', 'conversation', 'messages'],
  terminal: ['terminal page', 'terminals page', 'terminal view'],
  tools: ['tools', 'tools page'],
  files: ['files', 'file browser', 'files page'],
  schedule: ['schedule', 'calendar', 'schedule page'],
});

export const POLITE_PREFIXES = Object.freeze([
  'please',
  'pls',
  'hey please',
  'hey pls',
  'hey',
  'can you',
  'can u',
  'could you',
  'could u',
  'would you',
  'would u',
  'will you',
  'will u',
  'i want you to',
  'i want u to',
  'i need you to',
  'i need u to',
  'go ahead and',
  'go ahead',
  'kindly',
  'just',
  'okay',
  'ok',
  'so',
  'oh',
  'oh and',
  'oh and also',
  'and',
  'and also',
  'and then',
  'also',
  'then',
  'finally',
  'actually',
  'now',
]);

export const NEGATION_PREFIXES = Object.freeze([
  'do not', "don't", 'dont', 'never', 'no need to', 'without',
]);

export const DISCOURSE_MARKERS = Object.freeze([
  'for example',
  'for instance',
  'e.g.',
  'the phrase',
  'the phrases',
  'the words',
  'the command',
  'documentation',
  'the docs',
  'tutorial',
  'benchmark',
  'test data',
  'quoted',
  'quote',
  'not a request',
  'not an instruction',
  'not a command',
  'when someone says',
  'when a user says',
  'if someone says',
  'if a user says',
  'someone might say',
  'someone could say',
  'a user might say',
  'a user can say',
  'we discussed',
  'we previously discussed',
  'previously',
  'earlier',
  'yesterday',
  'last time',
  'historical',
  'history',
  'i opened',
  'i launched',
  'i used',
  'we opened',
  'we launched',
  'we used',
  'means',
  'refers to',
  'is called',
  'would say',
  'could say',
  'might say',
  'should test',
  'ought to test',
  'mentions',
  'mention',
  'describes',
  'described',
  'describing',
  'talking about',
  'discussion',
  'fake transcript',
  'transcript says',
  'transcript said',
  'says',
  'said',
  'reported speech',
  'compare',
  'comparison',
  'imagine',
  'suppose',
]);

export const CONTENT_MEDIATORS = Object.freeze({
  terminal: [
    'documentation', 'document', 'docs', 'article', 'report', 'text', 'phrase',
    'sentence', 'quote', 'screenshot', 'image', 'picture', 'video', 'tutorial',
    'guide', 'example', 'examples', 'list', 'explanation', 'description',
    'instructions', 'string', 'message', 'website', 'webpage', 'link',
    'readme', 'file about', 'file containing', 'file named',
  ],
  background: [
    'documentation', 'document', 'article', 'report', 'text', 'phrase', 'sentence',
    'quote', 'screenshot', 'image', 'picture', 'video', 'tutorial', 'guide',
    'example', 'examples', 'code', 'string',
  ],
  button: [
    'documentation', 'document', 'article', 'report', 'phrase', 'sentence',
    'word', 'words', 'glossary', 'quote', 'screenshot', 'image', 'picture',
    'video', 'tutorial', 'guide', 'example', 'examples', 'code', 'string',
  ],
  panel: [
    'documentation', 'document', 'article', 'report', 'text', 'phrase', 'sentence',
    'quote', 'screenshot', 'image', 'picture', 'video', 'tutorial', 'guide',
    'example', 'examples',
  ],
  status: [
    'documentation', 'document', 'article', 'report', 'text', 'phrase', 'sentence',
    'quote', 'screenshot', 'image', 'picture', 'video', 'tutorial', 'guide',
    'example', 'examples', 'explanation', 'description', 'list',
  ],
  font: [
    'documentation', 'document', 'article', 'report', 'quote', 'screenshot',
    'image', 'picture', 'video', 'tutorial', 'guide', 'example', 'examples',
    'code', 'string',
  ],
  music: [
    'documentation', 'document', 'article', 'report', 'text', 'phrase', 'sentence',
    'quote', 'screenshot', 'image', 'picture', 'video', 'tutorial', 'guide',
    'example', 'examples', 'list', 'explanation',
  ],
  page: [
    'documentation', 'document', 'article', 'report', 'text', 'phrase', 'sentence',
    'quote', 'screenshot', 'image', 'picture', 'video', 'tutorial', 'guide',
    'example', 'examples', 'code', 'string', 'website', 'webpage', 'link',
    'file named', 'file containing',
  ],
});

export const CORRECTION_MARKERS = Object.freeze([
  'actually',
  'instead',
  'rather',
  'no wait',
  'wait',
  'scratch that',
  'changed my mind',
]);

export const FILLER_WORDS = new Set([
  'hey', 'please', 'pls', 'kindly', 'just', 'okay', 'ok', 'right', 'uh', 'um',
  'like', 'basically', 'really', 'quickly', 'now', 'for', 'me', 'the', 'a', 'an',
]);
