import type { PluginManifest, PluginStatus } from './types';

const token = (id: string, label: string, placeholder: string, help?: string) => ({
  id,
  label,
  placeholder,
  help,
  secret: true,
  required: true,
});

const text = (id: string, label: string, placeholder: string, help?: string) => ({
  id,
  label,
  placeholder,
  help,
  secret: false,
  required: true,
});

const IMPLEMENTED: PluginManifest[] = [
  {
    id: 'github',
    name: 'GitHub',
    description: 'Repositories, issues, pull requests, actions, and authenticated account context.',
    category: 'Developer Tools',
    authType: 'token',
    fields: [
      token(
        'token',
        'Personal access token',
        'github_pat_...',
        'Use a fine-grained token with only the repositories and permissions Jarvis needs.',
      ),
    ],
    status: 'implemented',
    docsUrl: 'https://github.com/settings/personal-access-tokens',
    help: 'Create a fine-grained personal access token. Jarvis tests it against the authenticated-user endpoint and never exposes it to terminals.',
    tools: [
      {
        name: 'identity',
        description: 'Read the connected GitHub account identity.',
        readOnly: true,
      },
      {
        name: 'repository_context',
        description: 'Describe repository capabilities available through this connection.',
        readOnly: true,
      },
    ],
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Design files, components, comments, variables, and design-system context.',
    category: 'Design',
    authType: 'token',
    fields: [
      token(
        'token',
        'Personal access token',
        'figd_...',
        'Create a personal access token in Figma settings.',
      ),
    ],
    status: 'implemented',
    docsUrl: 'https://www.figma.com/developers/api#access-tokens',
    help: 'Use a Figma personal access token. The connection test reads only the current user profile.',
    tools: [
      {
        name: 'identity',
        description: 'Read the connected Figma account identity.',
        readOnly: true,
      },
      {
        name: 'design_context',
        description: 'Expose the connector capability set to project agents.',
        readOnly: true,
      },
    ],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Database, authentication, storage, edge functions, and project API context.',
    category: 'Databases',
    authType: 'api_key',
    fields: [
      text('url', 'Project URL', 'https://your-project.supabase.co'),
      token(
        'key',
        'Project API key',
        'sb_publishable_... or service role key',
        'Prefer a publishable/anon key for read-only context. Service-role keys are highly privileged.',
      ),
    ],
    status: 'implemented',
    docsUrl: 'https://supabase.com/docs/guides/api/api-keys',
    help: 'Enter the project URL and an API key. Jarvis calls the REST root to validate the pair.',
    tools: [
      {
        name: 'connection_info',
        description: 'Read safe project endpoint metadata.',
        readOnly: true,
      },
      {
        name: 'schema_context',
        description: 'Describe available database connector capabilities.',
        readOnly: true,
      },
    ],
  },
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Store catalog, orders, customers, themes, and Admin API context.',
    category: 'Ecommerce',
    authType: 'token',
    fields: [
      text('store', 'Store domain', 'your-store.myshopify.com'),
      token(
        'token',
        'Admin API access token',
        'shpat_...',
        'Use a custom app token with minimum required Admin API scopes.',
      ),
    ],
    status: 'implemented',
    docsUrl:
      'https://shopify.dev/docs/apps/build/authentication-authorization/access-tokens/generate-app-access-tokens-admin',
    help: 'Enter the permanent myshopify.com domain and a custom-app Admin API token.',
    tools: [
      { name: 'shop_identity', description: 'Read connected shop identity.', readOnly: true },
      {
        name: 'commerce_context',
        description: 'Describe available Shopify capabilities.',
        readOnly: true,
      },
    ],
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Workspace, channels, messages, users, and collaboration context.',
    category: 'Communication',
    authType: 'token',
    fields: [
      token(
        'token',
        'Bot or user token',
        'xoxb-... or xoxp-...',
        'Use the narrowest OAuth scopes required for your workspace.',
      ),
    ],
    status: 'implemented',
    docsUrl: 'https://api.slack.com/authentication/token-types',
    help: 'Enter a Slack bot or user token. Jarvis validates it with auth.test.',
    tools: [
      {
        name: 'identity',
        description: 'Read workspace and authenticated identity.',
        readOnly: true,
      },
      {
        name: 'workspace_context',
        description: 'Describe available Slack capabilities.',
        readOnly: true,
      },
    ],
  },
  {
    id: 'mock-connector',
    name: 'Jarvis Mock Connector',
    description: 'Deterministic local connector for testing plugin setup and tool dispatch.',
    category: 'Developer Tools',
    authType: 'none',
    fields: [],
    status: 'implemented',
    help: 'No credentials required. Use this connector to verify the plugin runtime without network access.',
    tools: [
      { name: 'ping', description: 'Return a deterministic local response.', readOnly: true },
      { name: 'list_tools', description: 'List this connector manifest tools.', readOnly: true },
    ],
  },
];

const CATALOG_GROUPS: Record<string, string[]> = {
  'Developer Tools': [
    'GitLab',
    'Bitbucket',
    'Azure DevOps',
    'Sourcegraph',
    'Codeberg',
    'Gitea',
    'Jenkins',
    'CircleCI',
    'Travis CI',
    'Buildkite',
    'TeamCity',
    'Bamboo',
    'Codecov',
    'SonarQube',
    'Snyk',
    'Dependabot',
    'Renovate',
    'LaunchDarkly',
    'Split',
    'Harness',
    'PagerDuty',
    'Opsgenie',
    'Better Uptime',
    'Statuspage',
    'Postman',
    'Insomnia',
    'SwaggerHub',
    'Stoplight',
    'ReadMe',
    'Algolia',
    'Elastic',
    'Meilisearch',
  ],
  'Cloud & Hosting': [
    'Vercel',
    'Netlify',
    'Cloudflare',
    'AWS',
    'Microsoft Azure',
    'Google Cloud',
    'DigitalOcean',
    'Linode',
    'Vultr',
    'Heroku',
    'Railway',
    'Render',
    'Fly.io',
    'Platform.sh',
    'Cloudways',
    'OpenStack',
    'Cloudinary',
    'Fastly',
    'Akamai',
    'Backblaze B2',
    'Wasabi',
    'Oracle Cloud',
    'IBM Cloud',
    'Hetzner Cloud',
  ],
  Databases: [
    'Firebase',
    'MongoDB Atlas',
    'PostgreSQL',
    'MySQL',
    'MariaDB',
    'SQLite',
    'Redis',
    'Neon',
    'PlanetScale',
    'CockroachDB',
    'Timescale',
    'ClickHouse',
    'Snowflake',
    'BigQuery',
    'Databricks',
    'Redshift',
    'DynamoDB',
    'Cosmos DB',
    'Fauna',
    'Turso',
    'Upstash',
    'Pinecone',
    'Qdrant',
    'Weaviate',
    'Milvus',
    'Chroma',
    'SingleStore',
    'Couchbase',
    'Cassandra',
    'InfluxDB',
    'Astra DB',
    'Xata',
  ],
  Productivity: [
    'Notion',
    'Airtable',
    'Coda',
    'Evernote',
    'Obsidian',
    'Todoist',
    'Microsoft To Do',
    'Google Tasks',
    'Monday.com',
    'Smartsheet',
    'Basecamp',
    'Wrike',
    'Height',
    'Fibery',
    'Miro',
    'Mural',
    'Lucidchart',
    'Whimsical',
    'Calendly',
    'Cal.com',
    'Reclaim',
    'Motion',
    'Clockwise',
    'Sunsama',
  ],
  'Project Management': [
    'Linear',
    'Jira',
    'Trello',
    'Asana',
    'ClickUp',
    'Shortcut',
    'YouTrack',
    'Azure Boards',
    'GitHub Projects',
    'GitLab Issues',
    'Redmine',
    'Taiga',
    'OpenProject',
    'Plane',
    'Productboard',
    'Aha!',
  ],
  Communication: [
    'Discord',
    'Microsoft Teams',
    'Zoom',
    'Google Meet',
    'Telegram',
    'WhatsApp Business',
    'Signal',
    'Mattermost',
    'Rocket.Chat',
    'Twilio',
    'Vonage',
    'RingCentral',
    'Dialpad',
    'Intercom',
    'Crisp',
    'Front',
    'Help Scout',
    'Zendesk',
    'Freshdesk',
    'Gorgias',
    'Kustomer',
    'Drift',
    'Tawk.to',
  ],
  'Google Workspace': [
    'Gmail',
    'Google Calendar',
    'Google Drive',
    'Google Sheets',
    'Google Docs',
    'Google Slides',
    'Google Forms',
    'Google Contacts',
    'Google Chat',
    'Google Analytics',
    'Google Search Console',
    'YouTube',
  ],
  'Microsoft 365': [
    'Outlook',
    'OneDrive',
    'SharePoint',
    'Excel',
    'Word',
    'PowerPoint',
    'Microsoft Planner',
    'Microsoft Forms',
    'Dynamics 365',
    'Power BI',
    'Microsoft Graph',
    'OneNote',
  ],
  Ecommerce: [
    'WooCommerce',
    'BigCommerce',
    'Magento',
    'Squarespace Commerce',
    'Wix Stores',
    'Ecwid',
    'Etsy',
    'Amazon Seller Central',
    'eBay',
    'Walmart Marketplace',
    'Commerce Layer',
    'Saleor',
    'Medusa',
    'ShipStation',
    'Shippo',
    'EasyPost',
    'Printful',
    'Printify',
    'Klaviyo',
    'Recharge',
  ],
  Payments: [
    'Stripe',
    'PayPal',
    'Square',
    'Adyen',
    'Braintree',
    'Paddle',
    'Lemon Squeezy',
    'Chargebee',
    'Recurly',
    'Razorpay',
    'Mollie',
    'Wise',
    'Plaid',
    'GoCardless',
    'Xero',
    'QuickBooks',
    'FreshBooks',
    'Wave Accounting',
    'Sage Accounting',
    'Brex',
  ],
  'Sales & Marketing': [
    'Salesforce',
    'HubSpot',
    'Pipedrive',
    'Zoho CRM',
    'Close',
    'Copper',
    'Attio',
    'Apollo',
    'Mailchimp',
    'Campaign Monitor',
    'ConvertKit',
    'Brevo',
    'ActiveCampaign',
    'Customer.io',
    'Braze',
    'Marketo',
    'Pardot',
    'Segment',
    'RudderStack',
    'mParticle',
    'Hightouch',
    'Census',
  ],
  Analytics: [
    'Sentry',
    'Datadog',
    'New Relic',
    'Grafana',
    'Prometheus',
    'PostHog',
    'Mixpanel',
    'Amplitude',
    'Plausible',
    'Fathom Analytics',
    'Matomo',
    'Heap',
    'FullStory',
    'Hotjar',
    'LogRocket',
    'Honeycomb',
    'Rollbar',
    'Bugsnag',
    'Splunk',
    'Sumo Logic',
    'Loki',
    'OpenTelemetry',
  ],
  Design: [
    'Canva',
    'Framer',
    'Webflow',
    'Adobe Creative Cloud',
    'Adobe XD',
    'Sketch',
    'InVision',
    'Zeplin',
    'Penpot',
    'LottieFiles',
    'Storybook',
    'Chromatic',
    'Zeroheight',
    'Abstract',
  ],
  'AI & Data': [
    'OpenAI',
    'Anthropic',
    'Google Gemini',
    'Perplexity',
    'Hugging Face',
    'Replicate',
    'Cohere',
    'Mistral AI',
    'Groq',
    'Together AI',
    'OpenRouter',
    'ElevenLabs',
    'Deepgram',
    'AssemblyAI',
    'Stability AI',
    'Pinecone Assistant',
    'LangSmith',
    'Weights & Biases',
    'Comet',
    'Humanloop',
  ],
  'Content & CMS': [
    'WordPress',
    'Contentful',
    'Sanity',
    'Strapi',
    'Ghost',
    'Webiny',
    'Prismic',
    'DatoCMS',
    'Storyblok',
    'Directus',
    'Hygraph',
    'Builder.io',
    'Medium',
    'Dev.to',
    'Hashnode',
    'Substack',
  ],
  Infrastructure: [
    'Docker',
    'Kubernetes',
    'Terraform Cloud',
    'Pulumi',
    'Ansible',
    'Chef',
    'Puppet',
    'Nomad',
    'Vault',
    'Consul',
    'Argo CD',
    'Flux',
    'Helm',
    'Istio',
    'Linkerd',
    'Portainer',
  ],
  'Email & Messaging': [
    'Resend',
    'SendGrid',
    'Postmark',
    'Mailgun',
    'Amazon SES',
    'SparkPost',
    'Loops',
    'Courier',
    'Knock',
    'Novu',
    'OneSignal',
    'Pusher',
    'Ably',
    'Stream',
  ],
  Files: ['Dropbox', 'Box', 'Egnyte', 'ShareFile', 'Nextcloud', 'pCloud', 'Sync.com', 'WeTransfer'],
};

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

const implementedIds = new Set(IMPLEMENTED.map((plugin) => plugin.id));

const PLANNED: PluginManifest[] = Object.entries(CATALOG_GROUPS).flatMap(([category, names]) =>
  names
    .map((name) => ({ name, id: slugify(name) }))
    .filter(({ id }) => !implementedIds.has(id))
    .map(({ name, id }) => ({
      id,
      name,
      description: `${name} connector for authenticated context and MCP-style tools.`,
      category,
      authType: 'oauth' as const,
      fields: [],
      status: 'planned' as PluginStatus,
      help: 'Catalog entry only. Connection and tool execution are not enabled in this release.',
      tools: [],
    })),
);

export const PLUGIN_CATALOG: readonly PluginManifest[] = [...IMPLEMENTED, ...PLANNED];

export function getPluginManifest(id: string): PluginManifest | undefined {
  return PLUGIN_CATALOG.find((plugin) => plugin.id === id);
}

export function validatePluginCatalog(catalog = PLUGIN_CATALOG): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  for (const plugin of catalog) {
    if (!plugin.id || !plugin.name || !plugin.description || !plugin.category || !plugin.help) {
      errors.push(`${plugin.id || '<missing-id>'}: missing required metadata`);
    }
    if (ids.has(plugin.id)) errors.push(`${plugin.id}: duplicate id`);
    ids.add(plugin.id);
    const fieldIds = new Set<string>();
    for (const field of plugin.fields) {
      if (!field.id || !field.label) errors.push(`${plugin.id}: invalid field`);
      if (fieldIds.has(field.id)) errors.push(`${plugin.id}: duplicate field ${field.id}`);
      fieldIds.add(field.id);
    }
    if (plugin.status === 'implemented' && plugin.tools.length === 0) {
      errors.push(`${plugin.id}: implemented plugin has no tools`);
    }
  }
  return errors;
}
