import { buildCatalogEntry } from './providerRegistry';
import type { PluginManifest, PluginStatus } from './types';

const token = (id: string, label: string, placeholder: string, help?: string) => ({
  id,
  label,
  placeholder,
  help,
  secret: true,
  required: true,
});

const text = (id: string, label: string, placeholder: string, help?: string) => ({
  id,
  label,
  placeholder,
  help,
  secret: false,
  required: true,
});

const IMPLEMENTED_BASE: PluginManifest[] = [
  {
    id: 'github',
    name: 'GitHub',
    provider: 'GitHub',
    description: 'Repositories, issues, pull requests, actions, and authenticated account context.',
    category: 'Developer Tools',
    authType: 'token',
    fields: [
      token(
        'token',
        'Personal access token',
        'github_pat_...',
        'Use a fine-grained token with only the repositories and permissions VibeSpace needs.',
      ),
    ],
    status: 'implemented',
    docsUrl: 'https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens',
    credentialUrl: 'https://github.com/settings/personal-access-tokens',
    help: 'Create a fine-grained personal access token. VibeSpace tests it against the authenticated-user endpoint and never exposes it to terminals.',
    tags: ['developer tools', 'git', 'token', 'repositories'],
    setupSteps: [
      'Open GitHub Settings → Developer settings → Personal access tokens.',
      'Create a fine-grained token with the repositories you need.',
      'Paste the token here and run Test Connection.',
    ],
    supportedFeatures: ['repositories', 'issues', 'pull requests', 'actions'],
    tools: [
      {
        name: 'identity',
        description: 'Read the connected GitHub account identity.',
        readOnly: true,
      },
      {
        name: 'repository_context',
        description: 'Describe repository capabilities available through this connection.',
        readOnly: true,
      },
    ],
    httpTest: {
      url: 'https://api.github.com/user',
      headers: {
        Accept: 'application/vnd.github+json',
        Authorization: 'Bearer {{token}}',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      accountLabelPath: 'login',
    },
  },
  {
    id: 'figma',
    name: 'Figma',
    provider: 'Figma',
    description: 'Design files, components, comments, variables, and design-system context.',
    category: 'Design',
    authType: 'token',
    fields: [
      token(
        'token',
        'Personal access token',
        'figd_...',
        'Create a personal access token in Figma settings.',
      ),
    ],
    status: 'implemented',
    docsUrl: 'https://www.figma.com/developers/api#access-tokens',
    credentialUrl: 'https://www.figma.com/developers/api#access-tokens',
    help: 'Use a Figma personal access token. The connection test reads only the current user profile.',
    tags: ['design', 'token', 'components'],
    setupSteps: [
      'Open Figma → Settings → Security → Personal access tokens.',
      'Generate a token and paste it here.',
      'Run Test Connection.',
    ],
    supportedFeatures: ['design files', 'components', 'comments'],
    tools: [
      {
        name: 'identity',
        description: 'Read the connected Figma account identity.',
        readOnly: true,
      },
      {
        name: 'design_context',
        description: 'Expose the connector capability set to project agents.',
        readOnly: true,
      },
    ],
    httpTest: {
      url: 'https://api.figma.com/v1/me',
      headers: { 'X-Figma-Token': '{{token}}' },
      accountLabelPath: 'email',
    },
  },
  {
    id: 'supabase',
    name: 'Supabase',
    provider: 'Supabase',
    description: 'Database, authentication, storage, edge functions, and project API context.',
    category: 'Databases',
    authType: 'api_key',
    fields: [
      text('url', 'Project URL', 'https://your-project.supabase.co'),
      token(
        'key',
        'Project API key',
        'sb_publishable_... or service role key',
        'Prefer a publishable/anon key for read-only context. Service-role keys are highly privileged.',
      ),
    ],
    status: 'implemented',
    docsUrl: 'https://supabase.com/docs/guides/api/api-keys',
    credentialUrl: 'https://supabase.com/dashboard/project/_/settings/api-keys',
    help: 'Enter the project URL and an API key. VibeSpace calls the REST root to validate the pair.',
    tags: ['database', 'auth', 'storage', 'api_key'],
    setupSteps: [
      'Open your Supabase project → Settings → API.',
      'Copy the project URL and publishable/anon key.',
      'Paste both values and test.',
    ],
    supportedFeatures: ['database', 'auth', 'storage', 'edge functions'],
    tools: [
      {
        name: 'connection_info',
        description: 'Read safe project endpoint metadata.',
        readOnly: true,
      },
      {
        name: 'schema_context',
        description: 'Describe available database connector capabilities.',
        readOnly: true,
      },
    ],
    httpTest: {
      url: '{{url}}/rest/v1/',
      headers: { apikey: '{{key}}', Authorization: 'Bearer {{key}}' },
      acceptEmpty: true,
    },
  },
  {
    id: 'shopify',
    name: 'Shopify',
    provider: 'Shopify',
    description: 'Store catalog, orders, customers, themes, and Admin API context.',
    category: 'Ecommerce',
    authType: 'token',
    fields: [
      text('store', 'Store domain', 'your-store.myshopify.com'),
      token(
        'token',
        'Admin API access token',
        'shpat_...',
        'Use a custom app token with minimum required Admin API scopes.',
      ),
    ],
    status: 'implemented',
    docsUrl:
      'https://shopify.dev/docs/apps/build/authentication-authorization/access-tokens/generate-app-access-tokens-admin',
    credentialUrl: 'https://admin.shopify.com/store/settings/apps/development',
    help: 'Enter the permanent myshopify.com domain and a custom-app Admin API token.',
    tags: ['ecommerce', 'token', 'orders'],
    setupSteps: [
      'Create a custom app in the Shopify admin.',
      'Install it and copy the Admin API access token.',
      'Enter store domain and token, then test.',
    ],
    supportedFeatures: ['catalog', 'orders', 'customers'],
    tools: [
      { name: 'shop_identity', description: 'Read connected shop identity.', readOnly: true },
      {
        name: 'commerce_context',
        description: 'Describe available Shopify capabilities.',
        readOnly: true,
      },
    ],
    httpTest: {
      url: 'https://{{store}}/admin/api/2026-04/shop.json',
      headers: { 'X-Shopify-Access-Token': '{{token}}' },
      accountLabelPath: 'shop.name',
    },
  },
  {
    id: 'slack',
    name: 'Slack',
    provider: 'Slack',
    description: 'Workspace, channels, messages, users, and collaboration context.',
    category: 'Communication',
    authType: 'token',
    fields: [
      token(
        'token',
        'Bot or user token',
        'xoxb-... or xoxp-...',
        'Use the narrowest OAuth scopes required for your workspace.',
      ),
    ],
    status: 'implemented',
    docsUrl: 'https://api.slack.com/authentication/token-types',
    credentialUrl: 'https://api.slack.com/apps',
    help: 'Enter a Slack bot or user token. VibeSpace validates it with auth.test.',
    tags: ['messaging', 'collaboration', 'token'],
    setupSteps: [
      'Create a Slack app at api.slack.com/apps.',
      'Install it to your workspace and copy the bot token.',
      'Paste the token and test.',
    ],
    supportedFeatures: ['channels', 'messages', 'users'],
    tools: [
      {
        name: 'identity',
        description: 'Read workspace and authenticated identity.',
        readOnly: true,
      },
      {
        name: 'workspace_context',
        description: 'Describe available Slack capabilities.',
        readOnly: true,
      },
    ],
    httpTest: {
      method: 'POST',
      url: 'https://slack.com/api/auth.test',
      headers: {
        Authorization: 'Bearer {{token}}',
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      accountLabelPath: 'team',
    },
  },
  {
    id: 'mock-connector',
    name: 'VibeSpace Mock Connector',
    provider: 'VibeSpace',
    description: 'Deterministic local connector for testing plugin setup and tool dispatch.',
    category: 'Developer Tools',
    authType: 'none',
    fields: [],
    status: 'implemented',
    help: 'No credentials required. Use this connector to verify the plugin runtime without network access.',
    tags: ['developer tools', 'local', 'testing'],
    setupSteps: ['Click Connect — no credentials are required.'],
    supportedFeatures: ['local testing'],
    tools: [
      { name: 'ping', description: 'Return a deterministic local response.', readOnly: true },
      { name: 'list_tools', description: 'List this connector manifest tools.', readOnly: true },
    ],
  },
];

const CATALOG_GROUPS: Record<string, string[]> = {
  'Developer Tools': [
    'GitLab',
    'Bitbucket',
    'Azure DevOps',
    'Sourcegraph',
    'Codeberg',
    'Gitea',
    'Jenkins',
    'CircleCI',
    'Travis CI',
    'Buildkite',
    'TeamCity',
    'Bamboo',
    'Codecov',
    'SonarQube',
    'Snyk',
    'Dependabot',
    'Renovate',
    'LaunchDarkly',
    'Split',
    'Harness',
    'PagerDuty',
    'Opsgenie',
    'Better Uptime',
    'Statuspage',
    'Postman',
    'Insomnia',
    'SwaggerHub',
    'Stoplight',
    'ReadMe',
    'Algolia',
    'Elastic',
    'Meilisearch',
  ],
  'Cloud & Hosting': [
    'Vercel',
    'Netlify',
    'Cloudflare',
    'AWS',
    'Microsoft Azure',
    'Google Cloud',
    'DigitalOcean',
    'Linode',
    'Vultr',
    'Heroku',
    'Railway',
    'Render',
    'Fly.io',
    'Platform.sh',
    'Cloudways',
    'OpenStack',
    'Cloudinary',
    'Fastly',
    'Akamai',
    'Backblaze B2',
    'Wasabi',
    'Oracle Cloud',
    'IBM Cloud',
    'Hetzner Cloud',
  ],
  Databases: [
    'Firebase',
    'MongoDB Atlas',
    'PostgreSQL',
    'MySQL',
    'MariaDB',
    'SQLite',
    'Redis',
    'Neon',
    'PlanetScale',
    'CockroachDB',
    'Timescale',
    'ClickHouse',
    'Snowflake',
    'BigQuery',
    'Databricks',
    'Redshift',
    'DynamoDB',
    'Cosmos DB',
    'Fauna',
    'Turso',
    'Upstash',
    'Pinecone',
    'Qdrant',
    'Weaviate',
    'Milvus',
    'Chroma',
    'SingleStore',
    'Couchbase',
    'Cassandra',
    'InfluxDB',
    'Astra DB',
    'Xata',
  ],
  Productivity: [
    'Notion',
    'Airtable',
    'Coda',
    'Evernote',
    'Obsidian',
    'Todoist',
    'Microsoft To Do',
    'Google Tasks',
    'Monday.com',
    'Smartsheet',
    'Basecamp',
    'Wrike',
    'Height',
    'Fibery',
    'Miro',
    'Mural',
    'Lucidchart',
    'Whimsical',
    'Calendly',
    'Cal.com',
    'Reclaim',
    'Motion',
    'Clockwise',
    'Sunsama',
  ],
  'Project Management': [
    'Linear',
    'Jira',
    'Trello',
    'Asana',
    'ClickUp',
    'Shortcut',
    'YouTrack',
    'Azure Boards',
    'GitHub Projects',
    'GitLab Issues',
    'Redmine',
    'Taiga',
    'OpenProject',
    'Plane',
    'Productboard',
    'Aha!',
  ],
  Communication: [
    'Discord',
    'Microsoft Teams',
    'Zoom',
    'Google Meet',
    'Telegram',
    'WhatsApp Business',
    'Signal',
    'Mattermost',
    'Rocket.Chat',
    'Twilio',
    'Vonage',
    'RingCentral',
    'Dialpad',
    'Intercom',
    'Crisp',
    'Front',
    'Help Scout',
    'Zendesk',
    'Freshdesk',
    'Gorgias',
    'Kustomer',
    'Drift',
    'Tawk.to',
  ],
  'Google Workspace': [
    'Gmail',
    'Google Calendar',
    'Google Drive',
    'Google Sheets',
    'Google Docs',
    'Google Slides',
    'Google Forms',
    'Google Contacts',
    'Google Chat',
    'Google Analytics',
    'Google Search Console',
    'YouTube',
  ],
  'Microsoft 365': [
    'Outlook',
    'OneDrive',
    'SharePoint',
    'Excel',
    'Word',
    'PowerPoint',
    'Microsoft Planner',
    'Microsoft Forms',
    'Dynamics 365',
    'Power BI',
    'Microsoft Graph',
    'OneNote',
  ],
  Ecommerce: [
    'WooCommerce',
    'BigCommerce',
    'Magento',
    'Squarespace Commerce',
    'Wix Stores',
    'Ecwid',
    'Etsy',
    'Amazon Seller Central',
    'eBay',
    'Walmart Marketplace',
    'Commerce Layer',
    'Saleor',
    'Medusa',
    'ShipStation',
    'Shippo',
    'EasyPost',
    'Printful',
    'Printify',
    'Klaviyo',
    'Recharge',
  ],
  Payments: [
    'Stripe',
    'PayPal',
    'Square',
    'Adyen',
    'Braintree',
    'Paddle',
    'Lemon Squeezy',
    'Chargebee',
    'Recurly',
    'Razorpay',
    'Mollie',
    'Wise',
    'Plaid',
    'GoCardless',
    'Xero',
    'QuickBooks',
    'FreshBooks',
    'Wave Accounting',
    'Sage Accounting',
    'Brex',
  ],
  'Sales & Marketing': [
    'Salesforce',
    'HubSpot',
    'Pipedrive',
    'Zoho CRM',
    'Close',
    'Copper',
    'Attio',
    'Apollo',
    'Mailchimp',
    'Campaign Monitor',
    'ConvertKit',
    'Brevo',
    'ActiveCampaign',
    'Customer.io',
    'Braze',
    'Marketo',
    'Pardot',
    'Segment',
    'RudderStack',
    'mParticle',
    'Hightouch',
    'Census',
  ],
  Analytics: [
    'Sentry',
    'Datadog',
    'New Relic',
    'Grafana',
    'Prometheus',
    'PostHog',
    'Mixpanel',
    'Amplitude',
    'Plausible',
    'Fathom Analytics',
    'Matomo',
    'Heap',
    'FullStory',
    'Hotjar',
    'LogRocket',
    'Honeycomb',
    'Rollbar',
    'Bugsnag',
    'Splunk',
    'Sumo Logic',
    'Loki',
    'OpenTelemetry',
  ],
  Design: [
    'Canva',
    'Framer',
    'Webflow',
    'Adobe Creative Cloud',
    'Adobe XD',
    'Sketch',
    'InVision',
    'Zeplin',
    'Penpot',
    'LottieFiles',
    'Storybook',
    'Chromatic',
    'Zeroheight',
    'Abstract',
  ],
  'AI & Data': [
    'OpenAI',
    'Anthropic',
    'Google Gemini',
    'Perplexity',
    'Hugging Face',
    'Replicate',
    'Cohere',
    'Mistral AI',
    'Groq',
    'Together AI',
    'OpenRouter',
    'ElevenLabs',
    'Deepgram',
    'AssemblyAI',
    'Stability AI',
    'Pinecone Assistant',
    'LangSmith',
    'Weights & Biases',
    'Comet',
    'Humanloop',
  ],
  'Content & CMS': [
    'WordPress',
    'Contentful',
    'Sanity',
    'Strapi',
    'Ghost',
    'Webiny',
    'Prismic',
    'DatoCMS',
    'Storyblok',
    'Directus',
    'Hygraph',
    'Builder.io',
    'Medium',
    'Dev.to',
    'Hashnode',
    'Substack',
  ],
  Infrastructure: [
    'Docker',
    'Kubernetes',
    'Terraform Cloud',
    'Pulumi',
    'Ansible',
    'Chef',
    'Puppet',
    'Nomad',
    'Vault',
    'Consul',
    'Argo CD',
    'Flux',
    'Helm',
    'Istio',
    'Linkerd',
    'Portainer',
  ],
  'Email & Messaging': [
    'Resend',
    'SendGrid',
    'Postmark',
    'Mailgun',
    'Amazon SES',
    'SparkPost',
    'Loops',
    'Courier',
    'Knock',
    'Novu',
    'OneSignal',
    'Pusher',
    'Ably',
    'Stream',
  ],
  Files: ['Dropbox', 'Box', 'Egnyte', 'ShareFile', 'Nextcloud', 'pCloud', 'Sync.com', 'WeTransfer'],
};

const implementedIds = new Set(IMPLEMENTED_BASE.map((plugin) => plugin.id));

const GENERATED: PluginManifest[] = Object.entries(CATALOG_GROUPS).flatMap(([category, names]) =>
  names
    .map((name) => buildCatalogEntry(name, category))
    .filter((plugin) => !implementedIds.has(plugin.id)),
);

export const PLUGIN_CATALOG: readonly PluginManifest[] = [...IMPLEMENTED_BASE, ...GENERATED];

export function getPluginManifest(id: string): PluginManifest | undefined {
  return PLUGIN_CATALOG.find((plugin) => plugin.id === id);
}

export function validatePluginCatalog(catalog = PLUGIN_CATALOG): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  for (const plugin of catalog) {
    if (
      !plugin.id ||
      !plugin.name ||
      !plugin.description ||
      !plugin.category ||
      !plugin.provider ||
      !plugin.help ||
      plugin.setupSteps.length === 0 ||
      plugin.tags.length === 0
    ) {
      errors.push(`${plugin.id || '<missing-id>'}: missing required metadata`);
    }
    if (ids.has(plugin.id)) errors.push(`${plugin.id}: duplicate id`);
    ids.add(plugin.id);
    const fieldIds = new Set<string>();
    for (const field of plugin.fields) {
      if (!field.id || !field.label) errors.push(`${plugin.id}: invalid field`);
      if (fieldIds.has(field.id)) errors.push(`${plugin.id}: duplicate field ${field.id}`);
      fieldIds.add(field.id);
    }
    if (plugin.status === 'implemented' && plugin.tools.length === 0) {
      errors.push(`${plugin.id}: implemented plugin has no tools`);
    }
    if (plugin.status === 'planned') {
      errors.push(`${plugin.id}: legacy planned status is not allowed`);
    }
    if (
      (plugin.status === 'implemented' || plugin.status === 'configurable') &&
      !plugin.httpTest &&
      plugin.authType !== 'none'
    ) {
      errors.push(`${plugin.id}: connectable plugin missing httpTest`);
    }
  }
  return errors;
}

export function catalogStats(catalog = PLUGIN_CATALOG) {
  const byStatus = (status: PluginStatus) => catalog.filter((p) => p.status === status).length;
  return {
    total: catalog.length,
    implemented: byStatus('implemented'),
    configurable: byStatus('configurable'),
    needsCredentials: byStatus('needs_credentials'),
    blocked: byStatus('blocked'),
    withHttpTest: catalog.filter((p) => Boolean(p.httpTest)).length,
  };
}
