import type {
  PluginAuthType,
  PluginField,
  PluginHttpTest,
  PluginManifest,
  PluginStatus,
  PluginTool,
} from './types';

type RegistryPartial = {
  provider?: string;
  description?: string;
  authType?: PluginAuthType;
  fields?: PluginField[];
  status?: PluginStatus;
  docsUrl?: string;
  credentialUrl?: string;
  help?: string;
  tags?: string[];
  setupSteps?: string[];
  supportedFeatures?: string[];
  limitations?: string;
  tools?: PluginTool[];
  httpTest?: PluginHttpTest;
};

const token = (id: string, label: string, placeholder: string, help?: string): PluginField => ({
  id,
  label,
  placeholder,
  help,
  secret: true,
  required: true,
});

const text = (id: string, label: string, placeholder: string, help?: string): PluginField => ({
  id,
  label,
  placeholder,
  help,
  secret: false,
  required: true,
});

const readTool = (name: string, description: string): PluginTool => ({
  name,
  description,
  readOnly: true,
});

const bearerTest = (url: string, tokenField = 'token', labelPath?: string): PluginHttpTest => ({
  url,
  headers: { Authorization: `Bearer {{${tokenField}}}` },
  accountLabelPath: labelPath,
});

const apiKeyHeaderTest = (
  url: string,
  header: string,
  field = 'api_key',
  labelPath?: string,
): PluginHttpTest => ({
  url,
  headers: { [header]: `{{${field}}}` },
  accountLabelPath: labelPath,
});

/** Official provider definitions with real connection probes where possible. */
export const PROVIDER_OVERRIDES: Record<string, RegistryPartial> = {
  openai: {
    provider: 'OpenAI',
    authType: 'api_key',
    fields: [token('api_key', 'API key', 'sk-...', 'Create a secret key with the minimum scopes you need.')],
    credentialUrl: 'https://platform.openai.com/api-keys',
    docsUrl: 'https://platform.openai.com/docs/api-reference',
    status: 'configurable',
    tags: ['ai', 'llm', 'api_key', 'models'],
    setupSteps: [
      'Sign in to the OpenAI platform.',
      'Open API keys and create a new secret key.',
      'Paste the key here and run Test Connection.',
    ],
    supportedFeatures: ['model routing', 'chat context'],
    httpTest: bearerTest('https://api.openai.com/v1/models', 'api_key', 'data.0.owned_by'),
    tools: [readTool('models_context', 'List accessible model families.')],
  },
  anthropic: {
    provider: 'Anthropic',
    authType: 'api_key',
    fields: [token('api_key', 'API key', 'sk-ant-...')],
    credentialUrl: 'https://console.anthropic.com/settings/keys',
    docsUrl: 'https://docs.anthropic.com/en/api/getting-started',
    status: 'configurable',
    tags: ['ai', 'llm', 'api_key'],
    setupSteps: [
      'Open the Anthropic Console.',
      'Create an API key under Settings → Keys.',
      'Paste the key and test the connection.',
    ],
    supportedFeatures: ['model routing', 'chat context'],
    httpTest: {
      url: 'https://api.anthropic.com/v1/models',
      headers: {
        'x-api-key': '{{api_key}}',
        'anthropic-version': '2023-06-01',
      },
    },
    tools: [readTool('models_context', 'Verify Anthropic API access.')],
  },
  groq: {
    provider: 'Groq',
    authType: 'api_key',
    fields: [token('api_key', 'API key', 'gsk_...')],
    credentialUrl: 'https://console.groq.com/keys',
    docsUrl: 'https://console.groq.com/docs/quickstart',
    status: 'configurable',
    tags: ['ai', 'llm', 'api_key', 'fast inference'],
    setupSteps: ['Create a GroqCloud API key.', 'Paste it here and test.'],
    supportedFeatures: ['fast inference', 'voice STT'],
    httpTest: bearerTest('https://api.groq.com/openai/v1/models', 'api_key'),
    tools: [readTool('models_context', 'List Groq models.')],
  },
  'google-gemini': {
    provider: 'Google',
    authType: 'api_key',
    fields: [token('api_key', 'Gemini API key', 'AIza...')],
    credentialUrl: 'https://aistudio.google.com/apikey',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    status: 'configurable',
    tags: ['ai', 'llm', 'google', 'api_key'],
    setupSteps: ['Open Google AI Studio.', 'Create an API key.', 'Paste and test.'],
    supportedFeatures: ['model routing', 'multimodal'],
    // Key travels in the x-goog-api-key header, never the URL (keeps it out of logs).
    httpTest: apiKeyHeaderTest(
      'https://generativelanguage.googleapis.com/v1beta/models',
      'x-goog-api-key',
      'api_key',
      'models.0.displayName',
    ),
    tools: [readTool('models_context', 'List Gemini models.')],
  },
  perplexity: {
    provider: 'Perplexity',
    authType: 'api_key',
    fields: [token('api_key', 'API key', 'pplx-...')],
    credentialUrl: 'https://www.perplexity.ai/settings/api',
    docsUrl: 'https://docs.perplexity.ai/guides/getting-started',
    status: 'configurable',
    tags: ['ai', 'search', 'api_key'],
    setupSteps: ['Generate a Perplexity API key.', 'Paste and test.'],
    supportedFeatures: ['search-augmented answers'],
    httpTest: bearerTest('https://api.perplexity.ai/models', 'api_key'),
    limitations: 'Uses a minimal API request during testing.',
    tools: [readTool('search_context', 'Search-augmented model access.')],
  },
  'hugging-face': {
    provider: 'Hugging Face',
    authType: 'token',
    fields: [token('token', 'Access token', 'hf_...')],
    credentialUrl: 'https://huggingface.co/settings/tokens',
    docsUrl: 'https://huggingface.co/docs/hub/security-tokens',
    status: 'configurable',
    tags: ['ai', 'models', 'token'],
    setupSteps: ['Create a Hugging Face access token with read access.', 'Paste and test.'],
    supportedFeatures: ['model hub', 'inference'],
    httpTest: bearerTest('https://huggingface.co/api/whoami-v2', 'token', 'name'),
    tools: [readTool('identity', 'Read Hugging Face account identity.')],
  },
  replicate: {
    provider: 'Replicate',
    authType: 'token',
    fields: [token('token', 'API token', 'r8_...')],
    credentialUrl: 'https://replicate.com/account/api-tokens',
    docsUrl: 'https://replicate.com/docs/reference/http',
    status: 'configurable',
    tags: ['ai', 'inference', 'token'],
    setupSteps: ['Create a Replicate API token.', 'Paste and test.'],
    supportedFeatures: ['model inference'],
    httpTest: bearerTest('https://api.replicate.com/v1/account', 'token', 'username'),
    tools: [readTool('account_context', 'Read Replicate account metadata.')],
  },
  cohere: {
    provider: 'Cohere',
    authType: 'api_key',
    fields: [token('api_key', 'API key', '...')],
    credentialUrl: 'https://dashboard.cohere.com/api-keys',
    docsUrl: 'https://docs.cohere.com/docs/the-cohere-platform',
    status: 'configurable',
    tags: ['ai', 'llm', 'api_key'],
    setupSteps: ['Create a Cohere API key.', 'Paste and test.'],
    supportedFeatures: ['embeddings', 'chat'],
    httpTest: bearerTest('https://api.cohere.com/v1/models', 'api_key'),
    tools: [readTool('models_context', 'List Cohere models.')],
  },
  'mistral-ai': {
    provider: 'Mistral AI',
    authType: 'api_key',
    fields: [token('api_key', 'API key', '...')],
    credentialUrl: 'https://console.mistral.ai/api-keys/',
    docsUrl: 'https://docs.mistral.ai/getting-started/quickstart/',
    status: 'configurable',
    tags: ['ai', 'llm', 'api_key'],
    setupSteps: ['Create a Mistral API key.', 'Paste and test.'],
    supportedFeatures: ['chat', 'embeddings'],
    httpTest: bearerTest('https://api.mistral.ai/v1/models', 'api_key'),
    tools: [readTool('models_context', 'List Mistral models.')],
  },
  'together-ai': {
    provider: 'Together AI',
    authType: 'api_key',
    fields: [token('api_key', 'API key', '...')],
    credentialUrl: 'https://api.together.ai/settings/api-keys',
    docsUrl: 'https://docs.together.ai/docs/quickstart',
    status: 'configurable',
    tags: ['ai', 'inference', 'api_key'],
    setupSteps: ['Create a Together API key.', 'Paste and test.'],
    supportedFeatures: ['open models', 'inference'],
    httpTest: bearerTest('https://api.together.xyz/v1/models', 'api_key'),
    tools: [readTool('models_context', 'List Together models.')],
  },
  openrouter: {
    provider: 'OpenRouter',
    authType: 'api_key',
    fields: [token('api_key', 'API key', 'sk-or-...')],
    credentialUrl: 'https://openrouter.ai/keys',
    docsUrl: 'https://openrouter.ai/docs',
    status: 'configurable',
    tags: ['ai', 'gateway', 'api_key'],
    setupSteps: ['Create an OpenRouter API key.', 'Paste and test.'],
    supportedFeatures: ['multi-provider routing'],
    httpTest: bearerTest('https://openrouter.ai/api/v1/auth/key', 'api_key', 'data.label'),
    tools: [readTool('routing_context', 'Read OpenRouter key metadata.')],
  },
  elevenlabs: {
    provider: 'ElevenLabs',
    authType: 'api_key',
    fields: [token('api_key', 'API key', '...')],
    credentialUrl: 'https://elevenlabs.io/app/settings/api-keys',
    docsUrl: 'https://elevenlabs.io/docs/api-reference/getting-started',
    status: 'configurable',
    tags: ['voice', 'tts', 'api_key'],
    setupSteps: ['Create an ElevenLabs API key.', 'Paste and test.'],
    supportedFeatures: ['text-to-speech'],
    httpTest: apiKeyHeaderTest('https://api.elevenlabs.io/v1/user', 'xi-api-key', 'api_key', 'subscription.tier'),
    tools: [readTool('voice_context', 'Read ElevenLabs account tier.')],
  },
  deepgram: {
    provider: 'Deepgram',
    authType: 'api_key',
    fields: [token('api_key', 'API key', '...')],
    credentialUrl: 'https://console.deepgram.com/project/default/keys',
    docsUrl: 'https://developers.deepgram.com/docs/create-additional-api-keys',
    status: 'configurable',
    tags: ['voice', 'stt', 'api_key'],
    setupSteps: ['Create a Deepgram API key.', 'Paste and test.'],
    supportedFeatures: ['speech-to-text'],
    httpTest: {
      url: 'https://api.deepgram.com/v1/projects',
      headers: { Authorization: 'Token {{api_key}}' },
    },
    tools: [readTool('voice_context', 'List Deepgram projects.')],
  },
  stripe: {
    provider: 'Stripe',
    authType: 'api_key',
    fields: [
      token('secret_key', 'Secret key', 'sk_live_... or sk_test_...', 'Use a restricted key when possible.'),
    ],
    credentialUrl: 'https://dashboard.stripe.com/apikeys',
    docsUrl: 'https://docs.stripe.com/keys',
    status: 'configurable',
    tags: ['payments', 'api_key', 'billing'],
    setupSteps: [
      'Open Stripe Dashboard → Developers → API keys.',
      'Copy the secret key (test or live).',
      'Paste and test.',
    ],
    supportedFeatures: ['billing', 'checkout context'],
    httpTest: {
      url: 'https://api.stripe.com/v1/balance',
      headers: { Authorization: 'Basic {{stripe_basic}}' },
    },
    tools: [readTool('billing_context', 'Read Stripe account balance metadata.')],
  },
  discord: {
    provider: 'Discord',
    authType: 'token',
    fields: [token('token', 'Bot token', '...', 'Create a bot in the Discord Developer Portal.')],
    credentialUrl: 'https://discord.com/developers/applications',
    docsUrl: 'https://discord.com/developers/docs/intro',
    status: 'configurable',
    tags: ['messaging', 'community', 'token'],
    setupSteps: ['Create an application and bot.', 'Copy the bot token.', 'Paste and test.'],
    supportedFeatures: ['messaging', 'community bots'],
    httpTest: {
      url: 'https://discord.com/api/v10/users/@me',
      headers: { Authorization: 'Bot {{token}}' },
      accountLabelPath: 'username',
    },
    tools: [readTool('identity', 'Read bot identity.')],
  },
  twilio: {
    provider: 'Twilio',
    authType: 'api_key',
    fields: [
      text('account_sid', 'Account SID', 'AC...'),
      token('auth_token', 'Auth token', '...'),
    ],
    credentialUrl: 'https://console.twilio.com/',
    docsUrl: 'https://www.twilio.com/docs/usage/api',
    status: 'configurable',
    tags: ['messaging', 'voice', 'sms'],
    setupSteps: [
      'Copy Account SID and Auth Token from the Twilio Console.',
      'Paste both values and test.',
    ],
    supportedFeatures: ['sms', 'voice', 'calling'],
    httpTest: {
      url: 'https://api.twilio.com/2010-04-01/Accounts/{{account_sid}}.json',
      headers: { Authorization: 'Basic {{basic_auth}}' },
      accountLabelPath: 'friendly_name',
    },
    limitations: 'Credentials are encoded for the test request only; secrets are never logged.',
    tools: [readTool('account_context', 'Read Twilio account metadata.')],
  },
  notion: {
    provider: 'Notion',
    authType: 'token',
    fields: [token('token', 'Integration token', 'secret_...')],
    credentialUrl: 'https://www.notion.so/my-integrations',
    docsUrl: 'https://developers.notion.com/docs/create-a-notion-integration',
    status: 'configurable',
    tags: ['productivity', 'notes', 'token'],
    setupSteps: ['Create an internal integration.', 'Copy the internal integration secret.', 'Share pages with the integration.'],
    supportedFeatures: ['notes', 'databases'],
    httpTest: {
      url: 'https://api.notion.com/v1/users/me',
      headers: {
        Authorization: 'Bearer {{token}}',
        'Notion-Version': '2022-06-28',
      },
      accountLabelPath: 'name',
    },
    tools: [readTool('workspace_context', 'Read Notion bot identity.')],
  },
  linear: {
    provider: 'Linear',
    authType: 'token',
    fields: [token('token', 'Personal API key', 'lin_api_...')],
    credentialUrl: 'https://linear.app/settings/api',
    docsUrl: 'https://developers.linear.app/docs/graphql/working-with-the-graphql-api',
    status: 'configurable',
    tags: ['project management', 'issues', 'token'],
    setupSteps: ['Create a Linear personal API key.', 'Paste and test.'],
    supportedFeatures: ['issues', 'projects'],
    httpTest: {
      method: 'POST',
      url: 'https://api.linear.app/graphql',
      headers: {
        Authorization: '{{token}}',
        'Content-Type': 'application/json',
      },
      body: '{"query":"{ viewer { id name email } }"}',
      accountLabelPath: 'data.viewer.name',
    },
    tools: [readTool('issues_context', 'Read Linear workspace identity.')],
  },
  gitlab: {
    provider: 'GitLab',
    authType: 'token',
    fields: [token('token', 'Personal access token', 'glpat-...')],
    credentialUrl: 'https://gitlab.com/-/user_settings/personal_access_tokens',
    docsUrl: 'https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html',
    status: 'configurable',
    tags: ['developer tools', 'git', 'token'],
    setupSteps: ['Create a personal access token with api scope.', 'Paste and test.'],
    supportedFeatures: ['repositories', 'issues', 'merge requests'],
    httpTest: {
      url: 'https://gitlab.com/api/v4/user',
      headers: { 'PRIVATE-TOKEN': '{{token}}' },
      accountLabelPath: 'username',
    },
    tools: [readTool('identity', 'Read GitLab user identity.')],
  },
  bitbucket: {
    provider: 'Atlassian',
    authType: 'token',
    fields: [token('token', 'API token', '...')],
    credentialUrl: 'https://id.atlassian.com/manage-profile/security/api-tokens',
    docsUrl: 'https://developer.atlassian.com/cloud/bitbucket/rest/intro/',
    status: 'configurable',
    tags: ['developer tools', 'git', 'token'],
    setupSteps: ['Create an Atlassian API token.', 'Paste and test against Bitbucket.'],
    supportedFeatures: ['repositories', 'pull requests'],
    httpTest: bearerTest('https://api.bitbucket.org/2.0/user', 'token', 'username'),
    tools: [readTool('identity', 'Read Bitbucket user identity.')],
  },
  vercel: {
    provider: 'Vercel',
    authType: 'token',
    fields: [token('token', 'Access token', '...')],
    credentialUrl: 'https://vercel.com/account/settings/tokens',
    docsUrl: 'https://vercel.com/docs/rest-api',
    status: 'configurable',
    tags: ['hosting', 'deployment', 'token'],
    setupSteps: ['Create a Vercel access token.', 'Paste and test.'],
    supportedFeatures: ['deployments', 'projects'],
    httpTest: bearerTest('https://api.vercel.com/v2/user', 'token', 'user.username'),
    tools: [readTool('deploy_context', 'Read Vercel user identity.')],
  },
  netlify: {
    provider: 'Netlify',
    authType: 'token',
    fields: [token('token', 'Personal access token', '...')],
    credentialUrl: 'https://app.netlify.com/user/applications#personal-access-tokens',
    docsUrl: 'https://docs.netlify.com/api/get-started/',
    status: 'configurable',
    tags: ['hosting', 'deployment', 'token'],
    setupSteps: ['Create a Netlify personal access token.', 'Paste and test.'],
    supportedFeatures: ['sites', 'deployments'],
    httpTest: bearerTest('https://api.netlify.com/api/v1/user', 'token', 'email'),
    tools: [readTool('deploy_context', 'Read Netlify user identity.')],
  },
  digitalocean: {
    provider: 'DigitalOcean',
    authType: 'token',
    fields: [token('token', 'Personal access token', 'dop_v1_...')],
    credentialUrl: 'https://cloud.digitalocean.com/account/api/tokens',
    docsUrl: 'https://docs.digitalocean.com/reference/api/',
    status: 'configurable',
    tags: ['cloud', 'hosting', 'token'],
    setupSteps: ['Generate a DigitalOcean personal access token.', 'Paste and test.'],
    supportedFeatures: ['droplets', 'kubernetes'],
    httpTest: bearerTest('https://api.digitalocean.com/v2/account', 'token', 'account.email'),
    tools: [readTool('cloud_context', 'Read DigitalOcean account.')],
  },
  sendgrid: {
    provider: 'Twilio SendGrid',
    authType: 'api_key',
    fields: [token('api_key', 'API key', 'SG....')],
    credentialUrl: 'https://app.sendgrid.com/settings/api_keys',
    docsUrl: 'https://docs.sendgrid.com/ui/account-and-settings/api-keys',
    status: 'configurable',
    tags: ['email', 'api_key'],
    setupSteps: ['Create a SendGrid API key with mail send scope.', 'Paste and test.'],
    supportedFeatures: ['transactional email'],
    httpTest: bearerTest('https://api.sendgrid.com/v3/user/profile', 'api_key', 'username'),
    tools: [readTool('email_context', 'Read SendGrid profile.')],
  },
  resend: {
    provider: 'Resend',
    authType: 'api_key',
    fields: [token('api_key', 'API key', 're_...')],
    credentialUrl: 'https://resend.com/api-keys',
    docsUrl: 'https://resend.com/docs/api-reference/introduction',
    status: 'configurable',
    tags: ['email', 'api_key'],
    setupSteps: ['Create a Resend API key.', 'Paste and test.'],
    supportedFeatures: ['transactional email'],
    httpTest: bearerTest('https://api.resend.com/domains', 'api_key'),
    tools: [readTool('email_context', 'List Resend domains.')],
  },
  posthog: {
    provider: 'PostHog',
    authType: 'api_key',
    fields: [
      text('host', 'PostHog host', 'https://us.posthog.com', 'Use your region host.'),
      token('api_key', 'Personal API key', 'phx_...'),
    ],
    credentialUrl: 'https://us.posthog.com/settings/user-api-keys',
    docsUrl: 'https://posthog.com/docs/api',
    status: 'configurable',
    tags: ['analytics', 'api_key'],
    setupSteps: ['Create a personal API key in PostHog.', 'Paste host and key, then test.'],
    supportedFeatures: ['product analytics'],
    httpTest: {
      url: '{{host}}/api/users/@me/',
      headers: { Authorization: 'Bearer {{api_key}}' },
      accountLabelPath: 'email',
    },
    tools: [readTool('analytics_context', 'Read PostHog user identity.')],
  },
  sentry: {
    provider: 'Sentry',
    authType: 'token',
    fields: [token('token', 'Auth token', 'sntrys_...')],
    credentialUrl: 'https://sentry.io/settings/account/api/auth-tokens/',
    docsUrl: 'https://docs.sentry.io/api/auth/',
    status: 'configurable',
    tags: ['analytics', 'errors', 'token'],
    setupSteps: ['Create a Sentry user auth token.', 'Paste and test.'],
    supportedFeatures: ['error monitoring'],
    httpTest: bearerTest('https://sentry.io/api/0/', 'token'),
    tools: [readTool('errors_context', 'Verify Sentry API access.')],
  },
  datadog: {
    provider: 'Datadog',
    authType: 'api_key',
    fields: [
      token('api_key', 'API key', '...'),
      token('app_key', 'Application key', '...'),
    ],
    credentialUrl: 'https://app.datadoghq.com/organization-settings/api-keys',
    docsUrl: 'https://docs.datadoghq.com/api/latest/authentication/',
    status: 'configurable',
    tags: ['analytics', 'observability', 'api_key'],
    setupSteps: [
      'Create Datadog API and application keys.',
      'Paste both and test.',
    ],
    supportedFeatures: ['monitoring', 'logs'],
    httpTest: {
      url: 'https://api.datadoghq.com/api/v1/validate',
      headers: {
        'DD-API-KEY': '{{api_key}}',
        'DD-APPLICATION-KEY': '{{app_key}}',
      },
      acceptEmpty: true,
    },
    tools: [readTool('observability_context', 'Validate Datadog credentials.')],
  },
  airtable: {
    provider: 'Airtable',
    authType: 'token',
    fields: [token('token', 'Personal access token', 'pat...')],
    credentialUrl: 'https://airtable.com/create/tokens',
    docsUrl: 'https://airtable.com/developers/web/guides/personal-access-tokens',
    status: 'configurable',
    tags: ['productivity', 'database', 'token'],
    setupSteps: ['Create an Airtable personal access token.', 'Paste and test.'],
    supportedFeatures: ['tables', 'records'],
    httpTest: bearerTest('https://api.airtable.com/v0/meta/whoami', 'token', 'email'),
    tools: [readTool('records_context', 'Read Airtable identity.')],
  },
  trello: {
    provider: 'Atlassian',
    authType: 'token',
    fields: [
      text('api_key', 'API key', '...'),
      token('token', 'Token', '...'),
    ],
    credentialUrl: 'https://trello.com/power-ups/admin',
    docsUrl: 'https://developer.atlassian.com/cloud/trello/guides/rest-api/api-introduction/',
    status: 'configurable',
    tags: ['project management', 'boards'],
    setupSteps: [
      'Generate a Trello Power-Up API key and user token.',
      'Paste both values and test.',
    ],
    supportedFeatures: ['boards', 'cards'],
    httpTest: {
      url: 'https://api.trello.com/1/members/me?key={{api_key}}&token={{token}}',
      accountLabelPath: 'username',
    },
    tools: [readTool('boards_context', 'Read Trello member identity.')],
  },
  asana: {
    provider: 'Asana',
    authType: 'token',
    fields: [token('token', 'Personal access token', '...')],
    credentialUrl: 'https://app.asana.com/0/my-apps',
    docsUrl: 'https://developers.asana.com/docs/personal-access-token',
    status: 'configurable',
    tags: ['project management', 'tasks', 'token'],
    setupSteps: ['Create an Asana personal access token.', 'Paste and test.'],
    supportedFeatures: ['tasks', 'projects'],
    httpTest: bearerTest('https://app.asana.com/api/1.0/users/me', 'token', 'data.email'),
    tools: [readTool('tasks_context', 'Read Asana user identity.')],
  },
  hubspot: {
    provider: 'HubSpot',
    authType: 'token',
    fields: [token('token', 'Private app access token', 'pat-...')],
    credentialUrl: 'https://developers.hubspot.com/docs/api/private-apps',
    docsUrl: 'https://developers.hubspot.com/docs/api/intro-to-auth',
    status: 'configurable',
    tags: ['crm', 'sales', 'token'],
    setupSteps: ['Create a HubSpot private app and copy the access token.', 'Paste and test.'],
    supportedFeatures: ['crm', 'contacts'],
    httpTest: bearerTest('https://api.hubapi.com/integrations/v1/me', 'token', 'portalId'),
    tools: [readTool('crm_context', 'Read HubSpot portal metadata.')],
  },
  mailchimp: {
    provider: 'Intuit Mailchimp',
    authType: 'api_key',
    fields: [token('api_key', 'API key', '...-us1')],
    credentialUrl: 'https://admin.mailchimp.com/account/api/',
    docsUrl: 'https://mailchimp.com/developer/marketing/guides/quick-start/',
    status: 'configurable',
    tags: ['email', 'marketing', 'api_key'],
    setupSteps: ['Copy your Mailchimp API key.', 'Paste and test.'],
    supportedFeatures: ['email marketing', 'audiences'],
    httpTest: {
      url: 'https://{{datacenter}}.api.mailchimp.com/3.0/ping',
      headers: { Authorization: 'Bearer {{api_key}}' },
      acceptEmpty: true,
    },
    limitations: 'Datacenter suffix is parsed from the API key during testing.',
    tools: [readTool('marketing_context', 'Verify Mailchimp API access.')],
  },
  plaid: {
    provider: 'Plaid',
    authType: 'api_key',
    fields: [
      text('client_id', 'Client ID', '...'),
      token('secret', 'Secret', '...'),
    ],
    credentialUrl: 'https://dashboard.plaid.com/developers/keys',
    docsUrl: 'https://plaid.com/docs/api/',
    status: 'needs_credentials',
    tags: ['payments', 'banking', 'api_key'],
    setupSteps: [
      'Copy Plaid client ID and secret for your environment.',
      'Paste them here and save.',
      'Complete institution linking in the Plaid dashboard (Manual Setup Required).',
    ],
    supportedFeatures: ['bank linking'],
    limitations: 'Plaid requires institution linking after API credentials are saved.',
    tools: [readTool('finance_context', 'Bank linking capability metadata.')],
  },
  neon: {
    provider: 'Neon',
    authType: 'api_key',
    fields: [token('api_key', 'API key', '...')],
    credentialUrl: 'https://console.neon.tech/app/settings/api-keys',
    docsUrl: 'https://neon.tech/docs/reference/api-reference',
    status: 'configurable',
    tags: ['database', 'postgres', 'api_key'],
    setupSteps: ['Create a Neon API key.', 'Paste and test.'],
    supportedFeatures: ['postgres', 'branches'],
    httpTest: bearerTest('https://console.neon.tech/api/v2/users/me', 'api_key', 'email'),
    tools: [readTool('database_context', 'Read Neon account identity.')],
  },
  planetscale: {
    provider: 'PlanetScale',
    authType: 'token',
    fields: [
      text('org', 'Organization', 'your-org'),
      token('token', 'Service token', 'pscale_tkn_...'),
    ],
    credentialUrl: 'https://app.planetscale.com/settings/service-tokens',
    docsUrl: 'https://api-docs.planetscale.com/reference/service-tokens',
    status: 'configurable',
    tags: ['database', 'mysql', 'token'],
    setupSteps: ['Create a PlanetScale service token.', 'Enter org name and token, then test.'],
    supportedFeatures: ['mysql', 'schema branches'],
    httpTest: bearerTest('https://api.planetscale.com/v1/organizations/{{org}}', 'token', 'name'),
    tools: [readTool('database_context', 'Read PlanetScale organization.')],
  },
  upstash: {
    provider: 'Upstash',
    authType: 'api_key',
    fields: [
      token('email', 'Account email', 'you@example.com', 'Used with API key for management API.'),
      token('api_key', 'Management API key', '...'),
    ],
    credentialUrl: 'https://console.upstash.com/account/api',
    docsUrl: 'https://upstash.com/docs/devops/developer-api/introduction',
    status: 'configurable',
    tags: ['database', 'redis', 'api_key'],
    setupSteps: ['Create an Upstash management API key.', 'Paste email and key, then test.'],
    supportedFeatures: ['redis', 'kafka'],
    httpTest: {
      url: 'https://api.upstash.com/v2/redis/databases',
      headers: {
        Authorization: 'Basic {{basic_email_key}}',
      },
    },
    tools: [readTool('database_context', 'List Upstash Redis databases.')],
  },
  pinecone: {
    provider: 'Pinecone',
    authType: 'api_key',
    fields: [token('api_key', 'API key', '...')],
    credentialUrl: 'https://app.pinecone.io/organizations/keys',
    docsUrl: 'https://docs.pinecone.io/guides/get-started/overview',
    status: 'configurable',
    tags: ['vector', 'database', 'api_key'],
    setupSteps: ['Create a Pinecone API key.', 'Paste and test.'],
    supportedFeatures: ['vector search'],
    httpTest: bearerTest('https://api.pinecone.io/indexes', 'api_key'),
    tools: [readTool('vector_context', 'List Pinecone indexes.')],
  },
  cloudflare: {
    provider: 'Cloudflare',
    authType: 'token',
    fields: [token('token', 'API token', '...', 'Create a token with Account read access.')],
    credentialUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    docsUrl: 'https://developers.cloudflare.com/api/',
    status: 'configurable',
    tags: ['hosting', 'cdn', 'token'],
    setupSteps: ['Create a Cloudflare API token.', 'Paste and test.'],
    supportedFeatures: ['dns', 'workers', 'cdn'],
    httpTest: bearerTest('https://api.cloudflare.com/client/v4/user/tokens/verify', 'token', 'result.id'),
    tools: [readTool('cloud_context', 'Verify Cloudflare API access.')],
  },
  heroku: {
    provider: 'Heroku',
    authType: 'token',
    fields: [token('token', 'API key', '...')],
    credentialUrl: 'https://dashboard.heroku.com/account/applications',
    docsUrl: 'https://devcenter.heroku.com/articles/platform-api-reference',
    status: 'configurable',
    tags: ['hosting', 'paas', 'token'],
    setupSteps: ['Create a Heroku API key.', 'Paste and test.'],
    supportedFeatures: ['apps', 'dynos'],
    httpTest: bearerTest('https://api.heroku.com/account', 'token', 'email'),
    tools: [readTool('deploy_context', 'Read Heroku account identity.')],
  },
  railway: {
    provider: 'Railway',
    authType: 'token',
    fields: [token('token', 'Account token', '...')],
    credentialUrl: 'https://railway.com/account/tokens',
    docsUrl: 'https://docs.railway.com/reference/public-api',
    status: 'configurable',
    tags: ['hosting', 'deployment', 'token'],
    setupSteps: ['Create a Railway account token.', 'Paste and test.'],
    supportedFeatures: ['projects', 'deployments'],
    httpTest: bearerTest('https://backboard.railway.app/graphql/v2', 'token'),
    tools: [readTool('deploy_context', 'Verify Railway API access.')],
  },
  render: {
    provider: 'Render',
    authType: 'api_key',
    fields: [token('api_key', 'API key', 'rnd_...')],
    credentialUrl: 'https://dashboard.render.com/u/settings#api-keys',
    docsUrl: 'https://render.com/docs/api',
    status: 'configurable',
    tags: ['hosting', 'deployment', 'api_key'],
    setupSteps: ['Create a Render API key.', 'Paste and test.'],
    supportedFeatures: ['services', 'deployments'],
    httpTest: bearerTest('https://api.render.com/v1/services', 'api_key'),
    tools: [readTool('deploy_context', 'List Render services.')],
  },
  jira: {
    provider: 'Atlassian',
    authType: 'token',
    fields: [
      text('email', 'Atlassian account email', 'you@example.com'),
      token('token', 'API token', '...'),
    ],
    credentialUrl: 'https://id.atlassian.com/manage-profile/security/api-tokens',
    docsUrl: 'https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/',
    status: 'configurable',
    tags: ['project management', 'issues', 'token'],
    setupSteps: ['Create an Atlassian API token.', 'Paste email and token, then test.'],
    supportedFeatures: ['issues', 'projects'],
    httpTest: {
      url: 'https://api.atlassian.com/me',
      headers: { Authorization: 'Basic {{basic_email_key}}' },
      accountLabelPath: 'email',
    },
    tools: [readTool('issues_context', 'Read Atlassian account identity.')],
  },
  clickup: {
    provider: 'ClickUp',
    authType: 'token',
    fields: [token('token', 'Personal API token', 'pk_...')],
    credentialUrl: 'https://app.clickup.com/settings/apps',
    docsUrl: 'https://clickup.com/api',
    status: 'configurable',
    tags: ['project management', 'tasks', 'token'],
    setupSteps: ['Generate a ClickUp personal API token.', 'Paste and test.'],
    supportedFeatures: ['tasks', 'lists'],
    httpTest: bearerTest('https://api.clickup.com/api/v2/user', 'token', 'user.email'),
    tools: [readTool('tasks_context', 'Read ClickUp user identity.')],
  },
  shortcut: {
    provider: 'Shortcut',
    authType: 'token',
    fields: [token('token', 'API token', '...')],
    credentialUrl: 'https://app.shortcut.com/settings/account/api-tokens',
    docsUrl: 'https://developer.shortcut.com/api/rest/v3',
    status: 'configurable',
    tags: ['project management', 'stories', 'token'],
    setupSteps: ['Create a Shortcut API token.', 'Paste and test.'],
    supportedFeatures: ['stories', 'epics'],
    httpTest: bearerTest('https://api.app.shortcut.com/api/v3/member', 'token', 'profile.email_address'),
    tools: [readTool('issues_context', 'Read Shortcut member identity.')],
  },
  'mongodb-atlas': {
    provider: 'MongoDB',
    authType: 'api_key',
    fields: [
      text('public_key', 'Public key', '...'),
      token('private_key', 'Private key', '...'),
    ],
    credentialUrl: 'https://cloud.mongodb.com/v2#/account/publicApi',
    docsUrl: 'https://www.mongodb.com/docs/atlas/api/',
    status: 'configurable',
    tags: ['database', 'mongodb', 'api_key'],
    setupSteps: ['Create a MongoDB Atlas API key pair.', 'Paste both keys and test.'],
    supportedFeatures: ['clusters', 'database'],
    httpTest: {
      url: 'https://cloud.mongodb.com/api/atlas/v2/groups',
      headers: {
        Accept: 'application/vnd.atlas.2023-01-01+json',
        Authorization: 'Basic {{mongo_basic}}',
      },
    },
    limitations: 'Uses Atlas public API digest auth during testing.',
    tools: [readTool('database_context', 'List MongoDB Atlas projects.')],
  },
  turso: {
    provider: 'Turso',
    authType: 'token',
    fields: [token('token', 'API token', '...')],
    credentialUrl: 'https://turso.tech/app/settings/tokens',
    docsUrl: 'https://docs.turso.tech/api-reference',
    status: 'configurable',
    tags: ['database', 'sqlite', 'token'],
    setupSteps: ['Create a Turso API token.', 'Paste and test.'],
    supportedFeatures: ['sqlite', 'edge database'],
    httpTest: bearerTest('https://api.turso.tech/v1/organizations', 'token'),
    tools: [readTool('database_context', 'List Turso organizations.')],
  },
  qdrant: {
    provider: 'Qdrant',
    authType: 'api_key',
    fields: [
      text('cluster_url', 'Cluster URL', 'https://xyz.cloud.qdrant.io'),
      token('api_key', 'API key', '...'),
    ],
    credentialUrl: 'https://cloud.qdrant.io/',
    docsUrl: 'https://qdrant.tech/documentation/',
    status: 'configurable',
    tags: ['vector', 'database', 'api_key'],
    setupSteps: ['Copy cluster URL and API key.', 'Paste and test.'],
    supportedFeatures: ['vector search'],
    httpTest: apiKeyHeaderTest('{{cluster_url}}/collections', 'api-key', 'api_key'),
    tools: [readTool('vector_context', 'List Qdrant collections.')],
  },
  weaviate: {
    provider: 'Weaviate',
    authType: 'api_key',
    fields: [
      text('cluster_url', 'Cluster URL', 'https://xyz.weaviate.network'),
      token('api_key', 'API key', '...'),
    ],
    credentialUrl: 'https://console.weaviate.cloud/',
    docsUrl: 'https://weaviate.io/developers/weaviate',
    status: 'configurable',
    tags: ['vector', 'database', 'api_key'],
    setupSteps: ['Copy cluster URL and API key.', 'Paste and test.'],
    supportedFeatures: ['vector search'],
    httpTest: apiKeyHeaderTest('{{cluster_url}}/v1/meta', 'Authorization', 'api_key'),
    tools: [readTool('vector_context', 'Read Weaviate cluster metadata.')],
  },
  coda: {
    provider: 'Coda',
    authType: 'token',
    fields: [token('token', 'API token', '...')],
    credentialUrl: 'https://coda.io/account',
    docsUrl: 'https://coda.io/developers/apis/v1',
    status: 'configurable',
    tags: ['productivity', 'docs', 'token'],
    setupSteps: ['Create a Coda API token.', 'Paste and test.'],
    supportedFeatures: ['docs', 'tables'],
    httpTest: bearerTest('https://coda.io/apis/v1/whoami', 'token', 'email'),
    tools: [readTool('workspace_context', 'Read Coda account identity.')],
  },
  miro: {
    provider: 'Miro',
    authType: 'token',
    fields: [token('token', 'Access token', '...')],
    credentialUrl: 'https://miro.com/app/settings/user-profile/apps',
    docsUrl: 'https://developers.miro.com/reference/introduction',
    status: 'configurable',
    tags: ['productivity', 'whiteboard', 'token'],
    setupSteps: ['Create a Miro access token.', 'Paste and test.'],
    supportedFeatures: ['boards', 'collaboration'],
    httpTest: bearerTest('https://api.miro.com/v2/boards', 'token'),
    tools: [readTool('workspace_context', 'Verify Miro API access.')],
  },
  telegram: {
    provider: 'Telegram',
    authType: 'token',
    fields: [token('token', 'Bot token', '...')],
    credentialUrl: 'https://t.me/BotFather',
    docsUrl: 'https://core.telegram.org/bots/api',
    status: 'configurable',
    tags: ['messaging', 'bots', 'token'],
    setupSteps: ['Create a bot via BotFather.', 'Paste the bot token and test.'],
    supportedFeatures: ['messaging', 'bots'],
    httpTest: { url: 'https://api.telegram.org/bot{{token}}/getMe', accountLabelPath: 'result.username' },
    tools: [readTool('identity', 'Read Telegram bot identity.')],
  },
  zendesk: {
    provider: 'Zendesk',
    authType: 'token',
    fields: [
      text('subdomain', 'Subdomain', 'your-company'),
      text('email', 'Agent email', 'you@example.com'),
      token('token', 'API token', '...'),
    ],
    credentialUrl: 'https://support.zendesk.com/hc/en-us/articles/4408889192858',
    docsUrl: 'https://developer.zendesk.com/api-reference/',
    status: 'configurable',
    tags: ['support', 'tickets', 'token'],
    setupSteps: ['Enable API token access in Zendesk admin.', 'Paste subdomain, email, and token.'],
    supportedFeatures: ['tickets', 'support'],
    httpTest: {
      url: 'https://{{subdomain}}.zendesk.com/api/v2/users/me.json',
      headers: { Authorization: 'Basic {{basic_email_key}}' },
      accountLabelPath: 'user.email',
    },
    tools: [readTool('support_context', 'Read Zendesk user identity.')],
  },
  intercom: {
    provider: 'Intercom',
    authType: 'token',
    fields: [token('token', 'Access token', '...')],
    credentialUrl: 'https://app.intercom.com/a/apps/_/developer-hub',
    docsUrl: 'https://developers.intercom.com/docs/build-an-integration/learn/authentication',
    status: 'configurable',
    tags: ['support', 'messaging', 'token'],
    setupSteps: ['Create an Intercom access token.', 'Paste and test.'],
    supportedFeatures: ['messaging', 'contacts'],
    httpTest: bearerTest('https://api.intercom.io/me', 'token', 'email'),
    tools: [readTool('support_context', 'Read Intercom admin identity.')],
  },
  salesforce: {
    provider: 'Salesforce',
    authType: 'token',
    fields: [
      text('instance_url', 'Instance URL', 'https://your-org.my.salesforce.com'),
      token('token', 'Access token', '...'),
    ],
    credentialUrl: 'https://developer.salesforce.com/',
    docsUrl: 'https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/',
    status: 'configurable',
    tags: ['crm', 'sales', 'token'],
    setupSteps: ['Create a connected app and access token.', 'Paste instance URL and token.'],
    supportedFeatures: ['crm', 'accounts'],
    httpTest: bearerTest('{{instance_url}}/services/data/v59.0/', 'token'),
    tools: [readTool('crm_context', 'Verify Salesforce API access.')],
  },
  pipedrive: {
    provider: 'Pipedrive',
    authType: 'token',
    fields: [token('token', 'API token', '...')],
    credentialUrl: 'https://app.pipedrive.com/settings/api',
    docsUrl: 'https://developers.pipedrive.com/docs/api/v1',
    status: 'configurable',
    tags: ['crm', 'sales', 'token'],
    setupSteps: ['Copy your Pipedrive API token.', 'Paste and test.'],
    supportedFeatures: ['deals', 'contacts'],
    httpTest: bearerTest('https://api.pipedrive.com/v1/users/me', 'token', 'data.email'),
    tools: [readTool('crm_context', 'Read Pipedrive user identity.')],
  },
  segment: {
    provider: 'Segment',
    authType: 'token',
    fields: [token('token', 'Config API token', '...')],
    credentialUrl: 'https://app.segment.com/settings/account/api-access',
    docsUrl: 'https://segment.com/docs/api/public-api/',
    status: 'configurable',
    tags: ['analytics', 'cdp', 'token'],
    setupSteps: ['Create a Segment Config API token.', 'Paste and test.'],
    supportedFeatures: ['event routing', 'cdp'],
    httpTest: bearerTest('https://api.segmentapis.com/workspaces', 'token'),
    tools: [readTool('analytics_context', 'List Segment workspaces.')],
  },
  grafana: {
    provider: 'Grafana',
    authType: 'api_key',
    fields: [
      text('host', 'Grafana URL', 'https://your-org.grafana.net'),
      token('api_key', 'Service account token', 'glsa_...'),
    ],
    credentialUrl: 'https://grafana.com/docs/grafana/latest/administration/service-accounts/',
    docsUrl: 'https://grafana.com/docs/grafana/latest/developers/http_api/',
    status: 'configurable',
    tags: ['analytics', 'observability', 'api_key'],
    setupSteps: ['Create a Grafana service account token.', 'Paste host and token.'],
    supportedFeatures: ['dashboards', 'alerting'],
    httpTest: bearerTest('{{host}}/api/org', 'api_key', 'name'),
    tools: [readTool('observability_context', 'Read Grafana org metadata.')],
  },
  'new-relic': {
    provider: 'New Relic',
    authType: 'api_key',
    fields: [token('api_key', 'User API key', 'NRAK-...')],
    credentialUrl: 'https://one.newrelic.com/admin-portal/api-keys/home',
    docsUrl: 'https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/',
    status: 'configurable',
    tags: ['analytics', 'apm', 'api_key'],
    setupSteps: ['Create a New Relic user API key.', 'Paste and test.'],
    supportedFeatures: ['apm', 'monitoring'],
    httpTest: apiKeyHeaderTest('https://api.newrelic.com/v2/applications.json', 'X-Api-Key', 'api_key'),
    tools: [readTool('observability_context', 'List New Relic applications.')],
  },
  mixpanel: {
    provider: 'Mixpanel',
    authType: 'api_key',
    fields: [
      text('project_id', 'Project ID', '123456'),
      token('api_secret', 'API secret', '...'),
    ],
    credentialUrl: 'https://mixpanel.com/settings/project',
    docsUrl: 'https://developer.mixpanel.com/reference/overview',
    status: 'configurable',
    tags: ['analytics', 'product', 'api_key'],
    setupSteps: ['Copy project ID and API secret.', 'Paste and test.'],
    supportedFeatures: ['product analytics'],
    httpTest: bearerTest('https://mixpanel.com/api/app/me', 'api_secret', 'results.email'),
    tools: [readTool('analytics_context', 'Verify Mixpanel API access.')],
  },
  woocommerce: {
    provider: 'WooCommerce',
    authType: 'api_key',
    fields: [
      text('store_url', 'Store URL', 'https://your-store.com'),
      text('consumer_key', 'Consumer key', 'ck_...'),
      token('consumer_secret', 'Consumer secret', 'cs_...'),
    ],
    credentialUrl: 'https://woocommerce.com/document/woocommerce-rest-api/',
    docsUrl: 'https://woocommerce.github.io/woocommerce-rest-api-docs/',
    status: 'configurable',
    tags: ['ecommerce', 'woocommerce', 'api_key'],
    setupSteps: ['Create REST API keys in WooCommerce settings.', 'Paste store URL and keys.'],
    supportedFeatures: ['catalog', 'orders'],
    httpTest: {
      url: '{{store_url}}/wp-json/wc/v3/system_status',
      headers: { Authorization: 'Basic {{woo_basic}}' },
    },
    tools: [readTool('commerce_context', 'Read WooCommerce system status.')],
  },
  bigcommerce: {
    provider: 'BigCommerce',
    authType: 'token',
    fields: [
      text('store_hash', 'Store hash', 'abc123'),
      token('token', 'Access token', '...'),
    ],
    credentialUrl: 'https://developer.bigcommerce.com/docs/start/authentication',
    docsUrl: 'https://developer.bigcommerce.com/docs/rest-management',
    status: 'configurable',
    tags: ['ecommerce', 'token'],
    setupSteps: ['Create a BigCommerce API account.', 'Paste store hash and token.'],
    supportedFeatures: ['catalog', 'orders'],
    httpTest: {
      url: 'https://api.bigcommerce.com/stores/{{store_hash}}/v2/store',
      headers: { 'X-Auth-Token': '{{token}}' },
      accountLabelPath: 'name',
    },
    tools: [readTool('commerce_context', 'Read BigCommerce store identity.')],
  },
  klaviyo: {
    provider: 'Klaviyo',
    authType: 'api_key',
    fields: [token('api_key', 'Private API key', 'pk_...')],
    credentialUrl: 'https://www.klaviyo.com/settings/account/api-keys',
    docsUrl: 'https://developers.klaviyo.com/en/reference/api_overview',
    status: 'configurable',
    tags: ['ecommerce', 'marketing', 'api_key'],
    setupSteps: ['Create a Klaviyo private API key.', 'Paste and test.'],
    supportedFeatures: ['email marketing', 'segments'],
    httpTest: apiKeyHeaderTest('https://a.klaviyo.com/api/accounts/', 'Authorization', 'api_key'),
    tools: [readTool('marketing_context', 'List Klaviyo accounts.')],
  },
  square: {
    provider: 'Square',
    authType: 'token',
    fields: [token('token', 'Access token', 'EAAA...')],
    credentialUrl: 'https://developer.squareup.com/apps',
    docsUrl: 'https://developer.squareup.com/docs/build-basics/access-tokens',
    status: 'configurable',
    tags: ['payments', 'pos', 'token'],
    setupSteps: ['Create a Square access token.', 'Paste and test.'],
    supportedFeatures: ['payments', 'catalog'],
    httpTest: bearerTest('https://connect.squareup.com/v2/locations', 'token'),
    tools: [readTool('payments_context', 'List Square locations.')],
  },
  paddle: {
    provider: 'Paddle',
    authType: 'api_key',
    fields: [token('api_key', 'API key', '...')],
    credentialUrl: 'https://vendors.paddle.com/authentication',
    docsUrl: 'https://developer.paddle.com/api-reference/about/authentication',
    status: 'configurable',
    tags: ['payments', 'billing', 'api_key'],
    setupSteps: ['Copy your Paddle API key.', 'Paste and test.'],
    supportedFeatures: ['subscriptions', 'billing'],
    httpTest: bearerTest('https://api.paddle.com/event-types', 'api_key'),
    tools: [readTool('payments_context', 'Verify Paddle API access.')],
  },
  'lemon-squeezy': {
    provider: 'Lemon Squeezy',
    authType: 'api_key',
    fields: [token('api_key', 'API key', '...')],
    credentialUrl: 'https://app.lemonsqueezy.com/settings/api',
    docsUrl: 'https://docs.lemonsqueezy.com/api',
    status: 'configurable',
    tags: ['payments', 'billing', 'api_key'],
    setupSteps: ['Create a Lemon Squeezy API key.', 'Paste and test.'],
    supportedFeatures: ['subscriptions', 'checkout'],
    httpTest: bearerTest('https://api.lemonsqueezy.com/v1/stores', 'api_key'),
    tools: [readTool('payments_context', 'List Lemon Squeezy stores.')],
  },
  chargebee: {
    provider: 'Chargebee',
    authType: 'api_key',
    fields: [
      text('site', 'Site name', 'your-site'),
      token('api_key', 'API key', '...'),
    ],
    credentialUrl: 'https://www.chargebee.com/docs/2.0/api_keys.html',
    docsUrl: 'https://apidocs.chargebee.com/docs/api/',
    status: 'configurable',
    tags: ['payments', 'subscriptions', 'api_key'],
    setupSteps: ['Copy site name and API key.', 'Paste and test.'],
    supportedFeatures: ['subscriptions', 'billing'],
    httpTest: {
      url: 'https://{{site}}.chargebee.com/api/v2/customers',
      headers: { Authorization: 'Basic {{chargebee_basic}}' },
    },
    tools: [readTool('payments_context', 'Verify Chargebee API access.')],
  },
  wise: {
    provider: 'Wise',
    authType: 'token',
    fields: [token('token', 'API token', '...')],
    credentialUrl: 'https://wise.com/settings/api-tokens',
    docsUrl: 'https://docs.wise.com/api-docs',
    status: 'configurable',
    tags: ['payments', 'transfers', 'token'],
    setupSteps: ['Create a Wise API token.', 'Paste and test.'],
    supportedFeatures: ['transfers', 'balances'],
    httpTest: bearerTest('https://api.wise.com/v1/profiles', 'token'),
    tools: [readTool('finance_context', 'List Wise profiles.')],
  },
  contentful: {
    provider: 'Contentful',
    authType: 'token',
    fields: [token('token', 'Content management token', 'CFPAT-...')],
    credentialUrl: 'https://app.contentful.com/account/profile/cma_tokens',
    docsUrl: 'https://www.contentful.com/developers/docs/references/content-management-api/',
    status: 'configurable',
    tags: ['cms', 'content', 'token'],
    setupSteps: ['Create a Contentful management token.', 'Paste and test.'],
    supportedFeatures: ['content', 'entries'],
    httpTest: bearerTest('https://api.contentful.com/spaces', 'token'),
    tools: [readTool('content_context', 'List Contentful spaces.')],
  },
  sanity: {
    provider: 'Sanity',
    authType: 'token',
    fields: [token('token', 'API token', 'sk...')],
    credentialUrl: 'https://www.sanity.io/manage',
    docsUrl: 'https://www.sanity.io/docs/http-api',
    status: 'configurable',
    tags: ['cms', 'content', 'token'],
    setupSteps: ['Create a Sanity API token.', 'Paste and test.'],
    supportedFeatures: ['content', 'datasets'],
    httpTest: bearerTest('https://api.sanity.io/v2021-06-07/projects', 'token'),
    tools: [readTool('content_context', 'List Sanity projects.')],
  },
  strapi: {
    provider: 'Strapi',
    authType: 'token',
    fields: [
      text('host', 'Strapi URL', 'https://your-cms.example.com'),
      token('token', 'API token', '...'),
    ],
    credentialUrl: 'https://docs.strapi.io/dev-docs/configurations/api-tokens',
    docsUrl: 'https://docs.strapi.io/dev-docs/api/rest',
    status: 'configurable',
    tags: ['cms', 'headless', 'token'],
    setupSteps: ['Create a Strapi API token.', 'Paste host and token.'],
    supportedFeatures: ['content', 'api'],
    httpTest: bearerTest('{{host}}/api/users/me', 'token'),
    tools: [readTool('content_context', 'Read Strapi user identity.')],
  },
  wordpress: {
    provider: 'WordPress',
    authType: 'api_key',
    fields: [
      text('site_url', 'Site URL', 'https://your-site.com'),
      text('username', 'Username', 'admin'),
      token('app_password', 'Application password', 'xxxx xxxx xxxx xxxx'),
    ],
    credentialUrl: 'https://wordpress.org/documentation/article/application-passwords/',
    docsUrl: 'https://developer.wordpress.org/rest-api/',
    status: 'configurable',
    tags: ['cms', 'wordpress', 'api_key'],
    setupSteps: ['Create a WordPress application password.', 'Paste site URL, username, and password.'],
    supportedFeatures: ['posts', 'pages'],
    httpTest: {
      url: '{{site_url}}/wp-json/wp/v2/users/me',
      headers: { Authorization: 'Basic {{wp_basic}}' },
      accountLabelPath: 'name',
    },
    tools: [readTool('content_context', 'Read WordPress user identity.')],
  },
  docker: {
    provider: 'Docker',
    authType: 'token',
    fields: [token('token', 'Personal access token', 'dckr_pat_...')],
    credentialUrl: 'https://hub.docker.com/settings/security',
    docsUrl: 'https://docs.docker.com/reference/api/hub/latest/',
    status: 'configurable',
    tags: ['infrastructure', 'containers', 'token'],
    setupSteps: ['Create a Docker Hub access token.', 'Paste and test.'],
    supportedFeatures: ['images', 'repositories'],
    httpTest: bearerTest('https://hub.docker.com/v2/users/me', 'token', 'username'),
    tools: [readTool('infra_context', 'Read Docker Hub identity.')],
  },
  'terraform-cloud': {
    provider: 'HashiCorp',
    authType: 'token',
    fields: [token('token', 'User API token', '...')],
    credentialUrl: 'https://app.terraform.io/app/settings/tokens',
    docsUrl: 'https://developer.hashicorp.com/terraform/cloud-docs/api-docs',
    status: 'configurable',
    tags: ['infrastructure', 'iac', 'token'],
    setupSteps: ['Create a Terraform Cloud user token.', 'Paste and test.'],
    supportedFeatures: ['workspaces', 'runs'],
    httpTest: bearerTest('https://app.terraform.io/api/v2/account/details', 'token', 'username'),
    tools: [readTool('infra_context', 'Read Terraform Cloud account.')],
  },
  pulumi: {
    provider: 'Pulumi',
    authType: 'token',
    fields: [token('token', 'Access token', 'pul-...')],
    credentialUrl: 'https://app.pulumi.com/account/tokens',
    docsUrl: 'https://www.pulumi.com/docs/pulumi-cloud/cloud-rest-api/',
    status: 'configurable',
    tags: ['infrastructure', 'iac', 'token'],
    setupSteps: ['Create a Pulumi access token.', 'Paste and test.'],
    supportedFeatures: ['stacks', 'deployments'],
    httpTest: bearerTest('https://api.pulumi.com/api/user', 'token', 'githubLogin'),
    tools: [readTool('infra_context', 'Read Pulumi user identity.')],
  },
  mailgun: {
    provider: 'Mailgun',
    authType: 'api_key',
    fields: [
      text('domain', 'Sending domain', 'mg.example.com'),
      token('api_key', 'API key', 'key-...'),
    ],
    credentialUrl: 'https://app.mailgun.com/app/account/security/api_keys',
    docsUrl: 'https://documentation.mailgun.com/docs/mailgun/api-reference/',
    status: 'configurable',
    tags: ['email', 'api_key'],
    setupSteps: ['Copy Mailgun domain and API key.', 'Paste and test.'],
    supportedFeatures: ['transactional email'],
    httpTest: bearerTest('https://api.mailgun.net/v3/domains', 'api_key'),
    tools: [readTool('email_context', 'List Mailgun domains.')],
  },
  postmark: {
    provider: 'Postmark',
    authType: 'token',
    fields: [token('token', 'Server API token', '...')],
    credentialUrl: 'https://account.postmarkapp.com/servers',
    docsUrl: 'https://postmarkapp.com/developer/api/server-api',
    status: 'configurable',
    tags: ['email', 'token'],
    setupSteps: ['Copy a Postmark server API token.', 'Paste and test.'],
    supportedFeatures: ['transactional email'],
    httpTest: apiKeyHeaderTest('https://api.postmarkapp.com/server', 'X-Postmark-Server-Token', 'token', 'Name'),
    tools: [readTool('email_context', 'Read Postmark server metadata.')],
  },
  dropbox: {
    provider: 'Dropbox',
    authType: 'token',
    fields: [token('token', 'Access token', 'sl....')],
    credentialUrl: 'https://www.dropbox.com/developers/apps',
    docsUrl: 'https://www.dropbox.com/developers/documentation/http/documentation',
    status: 'configurable',
    tags: ['files', 'storage', 'token'],
    setupSteps: ['Create a Dropbox access token.', 'Paste and test.'],
    supportedFeatures: ['files', 'sharing'],
    httpTest: {
      url: 'https://api.dropboxapi.com/2/users/get_current_account',
      method: 'POST',
      headers: { Authorization: 'Bearer {{token}}' },
      accountLabelPath: 'email',
    },
    tools: [readTool('files_context', 'Read Dropbox account identity.')],
  },
  box: {
    provider: 'Box',
    authType: 'token',
    fields: [token('token', 'Developer token', '...')],
    credentialUrl: 'https://app.box.com/developers/console',
    docsUrl: 'https://developer.box.com/reference/',
    status: 'configurable',
    tags: ['files', 'storage', 'token'],
    setupSteps: ['Generate a Box developer token.', 'Paste and test.'],
    supportedFeatures: ['files', 'collaboration'],
    httpTest: bearerTest('https://api.box.com/2.0/users/me', 'token', 'login'),
    tools: [readTool('files_context', 'Read Box user identity.')],
  },
  sourcegraph: {
    provider: 'Sourcegraph',
    authType: 'token',
    fields: [
      text('host', 'Sourcegraph URL', 'https://sourcegraph.com'),
      token('token', 'Access token', 'sgp_...'),
    ],
    credentialUrl: 'https://sourcegraph.com/users/$YOUR_USERNAME/settings/tokens',
    docsUrl: 'https://sourcegraph.com/docs/api',
    status: 'configurable',
    tags: ['developer tools', 'code search', 'token'],
    setupSteps: ['Create a Sourcegraph access token.', 'Paste host and token.'],
    supportedFeatures: ['code search', 'repositories'],
    httpTest: bearerTest('{{host}}/.api/graphql', 'token'),
    tools: [readTool('code_context', 'Verify Sourcegraph API access.')],
  },
  postman: {
    provider: 'Postman',
    authType: 'api_key',
    fields: [token('api_key', 'API key', 'PMAK-...')],
    credentialUrl: 'https://go.postman.co/settings/me/api-keys',
    docsUrl: 'https://learning.postman.com/docs/developer/postman-api/authentication/',
    status: 'configurable',
    tags: ['developer tools', 'api', 'api_key'],
    setupSteps: ['Create a Postman API key.', 'Paste and test.'],
    supportedFeatures: ['collections', 'apis'],
    httpTest: apiKeyHeaderTest('https://api.getpostman.com/me', 'X-Api-Key', 'api_key', 'user.email'),
    tools: [readTool('api_context', 'Read Postman user identity.')],
  },
  algolia: {
    provider: 'Algolia',
    authType: 'api_key',
    fields: [
      text('app_id', 'Application ID', '...'),
      token('api_key', 'Admin API key', '...'),
    ],
    credentialUrl: 'https://dashboard.algolia.com/account/api-keys/all',
    docsUrl: 'https://www.algolia.com/doc/rest-api/search/',
    status: 'configurable',
    tags: ['search', 'api_key'],
    setupSteps: ['Copy Algolia application ID and admin API key.', 'Paste and test.'],
    supportedFeatures: ['search', 'indexing'],
    httpTest: {
      url: 'https://{{app_id}}-dsn.algolia.net/1/indexes',
      headers: { 'X-Algolia-Application-Id': '{{app_id}}', 'X-Algolia-API-Key': '{{api_key}}' },
    },
    tools: [readTool('search_context', 'List Algolia indexes.')],
  },
  'launchdarkly': {
    provider: 'LaunchDarkly',
    authType: 'token',
    fields: [token('token', 'Access token', 'api-...')],
    credentialUrl: 'https://app.launchdarkly.com/settings/tokens',
    docsUrl: 'https://launchdarkly.com/docs/api',
    status: 'configurable',
    tags: ['developer tools', 'feature flags', 'token'],
    setupSteps: ['Create a LaunchDarkly access token.', 'Paste and test.'],
    supportedFeatures: ['feature flags'],
    httpTest: bearerTest('https://app.launchdarkly.com/api/v2/projects', 'token'),
    tools: [readTool('flags_context', 'List LaunchDarkly projects.')],
  },
};

const OAUTH_CATEGORY_DEFAULTS: Partial<RegistryPartial> = {
  authType: 'oauth',
  status: 'configurable',
  fields: [
    text('client_id', 'Client ID', '...'),
    token('client_secret', 'Client secret', '...', 'Stored in the OS keychain only.'),
  ],
  setupSteps: [
    'Click Connect, then authorize in your browser.',
  ],
  supportedFeatures: ['authenticated context'],
  limitations: 'OAuth requires a one-time browser authorization after credentials are saved.',
  tools: [readTool('oauth_context', 'OAuth capability metadata after setup.')],
};

const CATEGORY_DEFAULTS: Record<string, Partial<RegistryPartial>> = {
  'Google Workspace': {
    ...OAUTH_CATEGORY_DEFAULTS,
    credentialUrl: 'https://console.cloud.google.com/apis/credentials',
    docsUrl: 'https://developers.google.com/workspace/guides/get-started',
    tags: ['google', 'oauth', 'productivity'],
  },
  'Microsoft 365': {
    ...OAUTH_CATEGORY_DEFAULTS,
    credentialUrl: 'https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade',
    docsUrl: 'https://learn.microsoft.com/graph/auth/',
    tags: ['microsoft', 'oauth', 'productivity'],
  },
  'AI & Data': {
    authType: 'api_key',
    status: 'needs_credentials',
    fields: [token('api_key', 'API key', '...')],
    setupSteps: [
      'Open the provider developer console.',
      'Create an API key or access token.',
      'Paste the credential here and run Test Connection.',
    ],
    supportedFeatures: ['ai context'],
    tags: ['ai', 'api_key'],
    tools: [readTool('capability_context', 'Provider capability metadata.')],
  },
  Payments: {
    authType: 'api_key',
    status: 'needs_credentials',
    fields: [token('secret_key', 'Secret / API key', '...')],
    setupSteps: [
      'Open the provider dashboard developer section.',
      'Create or copy the secret/API key.',
      'Paste and test.',
    ],
    supportedFeatures: ['payments', 'billing'],
    tags: ['payments', 'api_key'],
    tools: [readTool('payments_context', 'Payments capability metadata.')],
  },
  Databases: {
    authType: 'api_key',
    status: 'needs_credentials',
    fields: [
      text('connection_url', 'Connection URL or host', 'postgres://... or https://...'),
      token('credential', 'Password / API key', '...'),
    ],
    setupSteps: [
      'Copy the connection URL or API credentials from your database provider.',
      'Paste them here.',
      'Run Test Connection to validate what can be checked safely.',
    ],
    supportedFeatures: ['database context'],
    tags: ['database'],
    tools: [readTool('database_context', 'Database capability metadata.')],
  },
};

const GENERIC_DEFAULT: Partial<RegistryPartial> = {
  authType: 'token',
  status: 'needs_credentials',
  fields: [token('token', 'API token or key', '...')],
  setupSteps: [
    'Open the official developer console for this service.',
    'Create an API token or key with the minimum required scopes.',
    'Paste the credential here.',
    'Run Test Connection.',
  ],
  supportedFeatures: ['integration context'],
  tags: ['integration'],
  tools: [readTool('capability_context', 'Integration capability metadata.')],
};

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function defaultDescription(name: string, category: string): string {
  return `${name} integration for ${category.toLowerCase()} workflows, agent context, and MCP-style tools.`;
}

function mergeManifest(
  id: string,
  name: string,
  category: string,
  override?: RegistryPartial,
  categoryDefault?: Partial<RegistryPartial>,
): PluginManifest {
  const base = { ...GENERIC_DEFAULT, ...categoryDefault, ...override };
  const provider = base.provider ?? name;
  const status = base.status ?? 'needs_credentials';
  const authType = base.authType ?? 'token';
  const fields = base.fields ?? GENERIC_DEFAULT.fields ?? [];
  const docsUrl = base.docsUrl;
  const credentialUrl = base.credentialUrl ?? docsUrl;
  const setupSteps = base.setupSteps ?? GENERIC_DEFAULT.setupSteps ?? [];
  const tags = [...new Set([...(base.tags ?? []), category.toLowerCase(), authType])];
  const tools = base.tools ?? [readTool('capability_context', `${name} capability metadata.`)];
  const description = base.description ?? defaultDescription(name, category);
  const help =
    base.help ??
    (status === 'needs_credentials'
      ? 'Manual setup may be required. Follow the steps below, use the official credential link, then test the connection.'
      : 'Enter credentials from the official provider console, then test the connection.');

  return {
    id,
    name,
    description,
    category,
    provider,
    authType,
    fields,
    status,
    docsUrl,
    credentialUrl,
    help,
    tools,
    tags,
    setupSteps,
    supportedFeatures: base.supportedFeatures ?? ['integration context'],
    limitations: base.limitations,
    httpTest: base.httpTest,
  };
}

export function buildCatalogEntry(name: string, category: string): PluginManifest {
  const id = slugify(name);
  return mergeManifest(id, name, category, PROVIDER_OVERRIDES[id], CATEGORY_DEFAULTS[category]);
}

export function pluginSearchBlob(plugin: PluginManifest, connectionState?: string): string {
  return [
    plugin.name,
    plugin.provider,
    plugin.description,
    plugin.category,
    plugin.authType,
    plugin.status,
    connectionState ?? '',
    plugin.help,
    plugin.limitations ?? '',
    ...plugin.tags,
    ...plugin.supportedFeatures,
    ...plugin.fields.map((field) => `${field.label} ${field.id}`),
    ...plugin.setupSteps,
  ]
    .join(' ')
    .toLowerCase();
}
