import { ponytailFullInstructions } from './ponytail';

// Generated by the original upstream builder at the pinned v4.10.0 commit in
// explicit full mode. Keep VibeSpace activation policy separate from upstream
// content so the host does not maintain a second mode-filtering algorithm.
// License: app/.jarvis/skills/ponytail/LICENSE.txt.
const hostActivationPolicy =
  'Current VibeSpace /mode selection controls activation for this turn. These upstream coding rules apply only while Token Saver is selected; they do not override explicit user requirements or permission boundaries. For non-coding requests, answer normally and concisely.';

export const ponytailInstructions = [ponytailFullInstructions, hostActivationPolicy].join('\n\n');
