//! Project-local terminal agent coordination persistence.
//!
//! The frontend owns coordination semantics (records, locks, summaries).
//! Rust owns the filesystem guarantees the WebView cannot provide:
//! create the hidden `.vibespace` directory, append JSONL events, and
//! write current state snapshots through temp files under a process mutex.

use serde::Serialize;
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};

const COORD_DIR: &str = ".vibespace";
const README_FILE: &str = "README.md";
const EVENTS_FILE: &str = "agent-coordination.jsonl";
const STATE_FILE: &str = "agent-state.json";
const LOCKS_FILE: &str = "agent-locks.json";
const MAX_JSON_BYTES: usize = 1024 * 1024;
const README_CONTENT: &str = "# VibeSpace Agent Coordination\n\nThis directory is generated by VibeSpace agent coordination.\nDo not manually edit unless recovering from an agent crash.\nNo API keys, provider secrets, or private tokens should be stored here.\n";

static COORDINATION_WRITE_LOCK: OnceLock<Mutex<()>> = OnceLock::new();

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CoordinationSnapshotFiles {
    pub coordination_dir: String,
    pub state_json: Option<String>,
    pub locks_json: Option<String>,
    pub events_text: Option<String>,
}

fn write_lock() -> &'static Mutex<()> {
    COORDINATION_WRITE_LOCK.get_or_init(|| Mutex::new(()))
}

fn require_project_root(project_root: &str) -> Result<PathBuf, String> {
    let root = PathBuf::from(project_root);
    if !root.is_absolute() {
        return Err("not_absolute".to_string());
    }
    if !root.exists() {
        return Err("not_found".to_string());
    }
    if !root.is_dir() {
        return Err("not_a_dir".to_string());
    }
    Ok(root)
}

fn validate_json_text(content: &str) -> Result<(), String> {
    if content.len() > MAX_JSON_BYTES {
        return Err("too_large".to_string());
    }
    serde_json::from_str::<serde_json::Value>(content).map_err(|_| "not_json".to_string())?;
    Ok(())
}

fn ensure_coordination_dir(project_root: &Path) -> Result<PathBuf, String> {
    let dir = project_root.join(COORD_DIR);
    fs::create_dir_all(&dir).map_err(|e| format!("io: {}", e))?;
    let readme = dir.join(README_FILE);
    if !readme.exists() {
        write_atomic(&readme, README_CONTENT)?;
    }
    Ok(dir)
}

fn read_optional(path: &Path) -> Result<Option<String>, String> {
    match fs::read_to_string(path) {
        Ok(content) => Ok(Some(content)),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(err) => Err(format!("io: {}", err)),
    }
}

fn write_atomic(path: &Path, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("io: {}", e))?;
    }
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| "invalid_path".to_string())?;
    let tmp = path.with_file_name(format!(".{}.tmp", file_name));
    {
        let mut file = OpenOptions::new()
            .create(true)
            .truncate(true)
            .write(true)
            .open(&tmp)
            .map_err(|e| format!("io: {}", e))?;
        file.write_all(content.as_bytes())
            .map_err(|e| format!("io: {}", e))?;
        file.sync_all().map_err(|e| format!("io: {}", e))?;
    }
    if path.exists() {
        fs::remove_file(path).map_err(|e| format!("io: {}", e))?;
    }
    fs::rename(&tmp, path).map_err(|e| format!("io: {}", e))
}

fn append_jsonl(path: &Path, event_json: &str) -> Result<(), String> {
    validate_json_text(event_json)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("io: {}", e))?;
    }
    let mut file = OpenOptions::new()
        .create(true)
        .append(true)
        .open(path)
        .map_err(|e| format!("io: {}", e))?;
    file.write_all(event_json.trim().as_bytes())
        .map_err(|e| format!("io: {}", e))?;
    file.write_all(b"\n").map_err(|e| format!("io: {}", e))?;
    file.flush().map_err(|e| format!("io: {}", e))
}

fn write_snapshot_files(
    project_root: String,
    state_json: Option<String>,
    locks_json: Option<String>,
    event_json: Option<String>,
) -> Result<CoordinationSnapshotFiles, String> {
    let _guard = write_lock().lock().map_err(|_| "lock_poisoned".to_string())?;
    let root = require_project_root(&project_root)?;
    if let Some(content) = &state_json {
        validate_json_text(content)?;
    }
    if let Some(content) = &locks_json {
        validate_json_text(content)?;
    }
    if let Some(content) = &event_json {
        validate_json_text(content)?;
    }

    let dir = ensure_coordination_dir(&root)?;
    if let Some(content) = state_json {
        write_atomic(&dir.join(STATE_FILE), &content)?;
    }
    if let Some(content) = locks_json {
        write_atomic(&dir.join(LOCKS_FILE), &content)?;
    }
    if let Some(content) = event_json {
        append_jsonl(&dir.join(EVENTS_FILE), &content)?;
    }
    read_snapshot_files(&root)
}

fn read_snapshot_files(project_root: &Path) -> Result<CoordinationSnapshotFiles, String> {
    let dir = ensure_coordination_dir(project_root)?;
    Ok(CoordinationSnapshotFiles {
        coordination_dir: dir.to_string_lossy().to_string(),
        state_json: read_optional(&dir.join(STATE_FILE))?,
        locks_json: read_optional(&dir.join(LOCKS_FILE))?,
        events_text: read_optional(&dir.join(EVENTS_FILE))?,
    })
}

#[tauri::command]
pub fn agent_coordination_snapshot(project_root: String) -> Result<CoordinationSnapshotFiles, String> {
    let _guard = write_lock().lock().map_err(|_| "lock_poisoned".to_string())?;
    let root = require_project_root(&project_root)?;
    read_snapshot_files(&root)
}

#[tauri::command]
pub fn agent_coordination_register(
    project_root: String,
    state_json: String,
    event_json: String,
) -> Result<CoordinationSnapshotFiles, String> {
    write_snapshot_files(project_root, Some(state_json), None, Some(event_json))
}

#[tauri::command]
pub fn agent_coordination_heartbeat(
    project_root: String,
    state_json: String,
    event_json: String,
) -> Result<CoordinationSnapshotFiles, String> {
    write_snapshot_files(project_root, Some(state_json), None, Some(event_json))
}

#[tauri::command]
pub fn agent_coordination_lock_file(
    project_root: String,
    state_json: String,
    locks_json: String,
    event_json: String,
) -> Result<CoordinationSnapshotFiles, String> {
    write_snapshot_files(project_root, Some(state_json), Some(locks_json), Some(event_json))
}

#[tauri::command]
pub fn agent_coordination_release_file(
    project_root: String,
    state_json: String,
    locks_json: String,
    event_json: String,
) -> Result<CoordinationSnapshotFiles, String> {
    write_snapshot_files(project_root, Some(state_json), Some(locks_json), Some(event_json))
}

#[tauri::command]
pub fn agent_coordination_append_event(
    project_root: String,
    event_json: String,
) -> Result<CoordinationSnapshotFiles, String> {
    write_snapshot_files(project_root, None, None, Some(event_json))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_project_root() -> PathBuf {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = std::env::temp_dir().join(format!("vibespace-agent-coordination-{stamp}"));
        fs::create_dir_all(&root).unwrap();
        root
    }

    #[test]
    fn rejects_relative_project_roots() {
        let err = agent_coordination_snapshot("relative/path".to_string()).unwrap_err();
        assert_eq!(err, "not_absolute");
    }

    #[test]
    fn writes_state_and_locks_snapshots_under_vibespace_dir() {
        let root = temp_project_root();
        let out = agent_coordination_lock_file(
            root.to_string_lossy().to_string(),
            r#"{"agents":[]}"#.to_string(),
            r#"{"locks":[]}"#.to_string(),
            r#"{"type":"file_locked","summary":"locked"}"#.to_string(),
        )
        .unwrap();

        assert!(out.coordination_dir.ends_with(".vibespace"));
        assert_eq!(out.state_json.as_deref(), Some(r#"{"agents":[]}"#));
        assert_eq!(out.locks_json.as_deref(), Some(r#"{"locks":[]}"#));
        assert!(out.events_text.unwrap().contains(r#""file_locked""#));
        assert!(root.join(".vibespace").join("README.md").exists());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn appends_jsonl_events_without_overwriting_existing_events() {
        let root = temp_project_root();
        let project_root = root.to_string_lossy().to_string();
        agent_coordination_append_event(
            project_root.clone(),
            r#"{"type":"heartbeat","summary":"first"}"#.to_string(),
        )
        .unwrap();
        let out = agent_coordination_append_event(
            project_root,
            r#"{"type":"heartbeat","summary":"second"}"#.to_string(),
        )
        .unwrap();

        let events = out.events_text.unwrap();
        assert_eq!(events.lines().count(), 2);
        assert!(events.contains("first"));
        assert!(events.contains("second"));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn rejects_non_json_snapshot_payloads() {
        let root = temp_project_root();
        let err = agent_coordination_register(
            root.to_string_lossy().to_string(),
            "not-json".to_string(),
            r#"{"type":"agent_registered"}"#.to_string(),
        )
        .unwrap_err();

        assert_eq!(err, "not_json");
        let _ = fs::remove_dir_all(root);
    }
}
