/** Public database API. Runtime singleton consumers import the leaf module directly. */
export * from './database';
export { DB_NAME, DB_VERSION } from './schema';
export type {
  Workspace,
  Project,
  SettingsRow,
  SyncQueueRow,
  SyncOp,
  SyncStatus,
  StoreName,
  ContextMapRow,
  ContextSourceRow,
  ContextEntityRow,
  ContextEdgeRow,
  ContextProvenanceRow,
  ContextMigrationBackupRow,
  ContextQuarantineRow,
  ContextNoteRow,
  ContextNoteRevisionRow,
  ContextAssetRow,
  ContextEmbeddingRow,
  PromptForgeJobRow,
  MemoryEvidenceRow,
  MemoryEvidenceHistoryRow,
  CanvasDocumentRow,
  CanvasPageRow,
  CanvasObjectRow,
  CanvasSpatialRow,
  CanvasCameraRow,
  CanvasAssetRow,
  CanvasTemplateRow,
  CanvasRevisionRow,
  CanvasTombstoneRow,
  CanvasRecoveryRow,
  BrowserChatBindingRow,
  BrowserChatImportRow,
  BrowserChatPermissionProfileRow,
  BrowserChatSnapshotMessage,
  BrowserChatSnapshotRow,
  BrowserChatProvider,
  ProviderProjectLinkRow,
  CaoMissionRow,
  JevUsageRecordRow,
  CaoExecutionProfileRow,
} from './schema';
export * from './repositories';
export { seedIfEmpty } from './seed';
