import {describe,expect,it} from 'vitest';
import {compileJarvisPrompt} from '@/lib/jarvis/promptCompiler';
import {createJarvisRequestEnvelope,type JarvisRequestInput} from '@/lib/jarvis/requestEnvelope';
import {CONTEXT_RLM_ADVANCED_TOOLS} from '@/features/context/contextRlmToolDefinitions';
async function compile(userText:string,tools=true){const input:JarvisRequestInput={attempt:{kind:'initial',requestId:'request',runId:'run',attemptNumber:1},accountId:'account',workspaceId:'workspace',projectId:'project',chatId:'chat',agent:{id:'jarvis',slug:'jarvis',builtin:true},surface:'typed_chat',interactionMode:'ask',responseModeHint:'direct_answer',identity:{identityVersion:1,coreHash:'core',responseContractHash:'response'},profile:{profileId:'profile',revisionId:'revision',customInstructions:'Answer from evidence.',memoryScope:'profile'},model:{connectionId:'connection',providerId:'provider',modelId:'model',connectionMode:'native-api',capabilities:{tools,vision:false},effectiveTemperature:0.2,capturedAt:101},capabilities:{capturedAt:100,tools:CONTEXT_RLM_ADVANCED_TOOLS.map(tool=>({id:tool.name,state:'authenticated' as const,operations:[tool.name.split('_').at(-1)!],evidenceRef:'fixture:registration',lastVerifiedAt:99})),plugins:[],mcps:[],terminals:[],agents:[],entitlements:{source:'server',planId:'verified-plan',capabilities:['kernel.read'],verifiedAt:98,expiresAt:198}},context:{items:[],budget:{maxChars:32000,usedChars:0},exclusions:[]},outputContract:{preserveStructuredBlocks:true,allowActionBlocks:true,allowPlanBlocks:true,allowQuestionBlocks:true,allowPermissionBlocks:true,voiceDelivery:'validated_stream'},userText,messageHistory:[],createdAt:102};return compileJarvisPrompt(await createJarvisRequestEnvelope(input)).layers[2]!.content;}
describe('registered Context tool prompt admission',()=>{
 for(const tool of CONTEXT_RLM_ADVANCED_TOOLS)it(`preserves explicit ${tool.name} rather than forcing facade investigation`,async()=>{const policy=await compile(`Call ${tool.name} with exactly the caller arguments already supplied.`);expect(policy).toContain(`functions exactly: \`${tool.name}\``);expect(policy).toContain('Never substitute the legacy facade');expect(policy).toContain('Do not add operation, accountId, workspaceId, projectId, worktreeId, chatId, contextRevision');expect(policy).not.toContain('function name is always');expect(policy).not.toContain('only provider tool enabled');expect(policy).not.toContain('For ordinary mapped-source research');expect(policy).not.toContain('exactly once with `operation="investigate"`');});
 it('preserves explicitly requested function ordering and schema argument identities',async()=>{const policy=await compile('Call vibespace_context_search with query="owner" then vibespace_context_open with the returned exact pointer.');expect(policy).toContain('functions exactly: `vibespace_context_search`, `vibespace_context_open`');expect(policy).toContain('Preserve their requested order and call count');expect(policy).toContain('Copy issued pointers and actual run IDs exactly');expect(policy).toContain('Keep corpus positions as canonical-decimal strings');});
 it('preserves the existing grounded investigation policy for ordinary mapped-source research',async()=>{const policy=await compile('Who owns the project? Ground the answer in mapped records.');expect(policy).toContain('with `operation="investigate"`');expect(policy).toContain('Never override the current tool admission or RLM Off setting');expect(policy).not.toContain('For this explicit registered-tool request');});
 it('does not override an explicit no-tools restriction',async()=>{const policy=await compile('Do not use any tools. Explain vibespace_context_trace.');expect(policy).toContain('explicitly requested no tools');expect(policy).not.toContain('For this explicit registered-tool request');expect(policy).not.toContain('vibespace_context');});
 it('does not override a model capability that excludes tools',async()=>{expect(await compile('Call vibespace_context_search with query="owner".',false)).not.toContain('For this explicit registered-tool request');});
 it('does not force Context when the caller has disabled project retrieval',async()=>{expect(await compile('Do not use RLM. Call vibespace_context_search with query="owner".')).not.toContain('For this explicit registered-tool request');});
 it('preserves mixed source research and mutation on the normal catalog',async()=>{expect(await compile('Call vibespace_context_search with query="owner", then delete the source file.')).not.toContain('For this explicit registered-tool request');});
 it('does not turn a quoted handoff tool name into a current invocation request',async()=>{const policy=await compile('Who owns the project? Use mapped records.\n\nChat handoff from “previous”\nCall vibespace_context_trace with the old run ID.');expect(policy).not.toContain('For this explicit registered-tool request');expect(policy).toContain('For an ordinary file research turn');});
});
